/**
 * Auto-update plumbing.
 *
 * Thin wrapper around `electron-updater`'s `autoUpdater`. Responsibilities:
 *   1. Translate autoUpdater events into renderer-friendly IPC payloads on
 *      two channels: `update:status` (lifecycle) and `update:progress`
 *      (download progress — separate so the renderer can throttle it).
 *   2. Register three invokable handlers so the renderer can drive the
 *      lifecycle manually: `update:check`, `update:download`, `update:install`.
 *   3. Kick off an initial check 5s after window-ready and re-check every
 *      6 hours so long-running sessions still notice new releases.
 *
 * Dev-mode guard: `electron-updater` throws immediately on unsigned builds
 * without an `app-update.yml`, which is every dev run. Callers MUST only
 * invoke `initAutoUpdater` when `app.isPackaged` is true; the function
 * re-asserts this as a safety net.
 *
 * Where update artifacts come from: `package.json.build.publish` points at
 * `willbearfruits/daisypatcher` on GitHub. At runtime electron-updater
 * reads the same config out of `app-update.yml` (generated by
 * electron-builder into the packaged resources) and polls the Releases API.
 */

import { app, BrowserWindow, ipcMain } from 'electron'
import type { ProgressInfo, UpdateInfo } from 'electron-updater'
import electronUpdater from 'electron-updater'

const { autoUpdater } = electronUpdater

/** How long to wait after the window is shown before the first check. */
const FIRST_CHECK_DELAY_MS = 5_000

/** Interval between recurring update checks while the app is open. */
const RECHECK_INTERVAL_MS = 6 * 60 * 60 * 1000

type StatusPayload =
  | { state: 'checking' }
  | { state: 'available'; version: string; releaseNotes: string | null }
  | { state: 'none'; version: string | null }
  | { state: 'downloaded'; version: string }
  | { state: 'error'; message: string }

interface ProgressPayload {
  percent: number
  bytesPerSecond: number
  transferred: number
  total: number
}

/**
 * Collapse electron-updater's polymorphic releaseNotes (string | array of
 * per-platform blobs | null) down to a single string for the renderer.
 */
function normalizeReleaseNotes(
  notes: UpdateInfo['releaseNotes']
): string | null {
  if (!notes) return null
  if (typeof notes === 'string') return notes
  if (Array.isArray(notes)) {
    return notes
      .map((n) => (typeof n === 'string' ? n : n.note ?? ''))
      .filter((s) => s.length > 0)
      .join('\n\n') || null
  }
  return null
}

function sendStatus(win: BrowserWindow, payload: StatusPayload): void {
  if (!win.isDestroyed()) {
    win.webContents.send('update:status', payload)
  }
}

function sendProgress(win: BrowserWindow, payload: ProgressPayload): void {
  if (!win.isDestroyed()) {
    win.webContents.send('update:progress', payload)
  }
}

/** Guard so repeated IPC handler registrations don't crash in HMR scenarios. */
let handlersRegistered = false

export function initAutoUpdater(win: BrowserWindow): void {
  // Belt-and-suspenders: we also check at the call site in index.ts, but if
  // someone ever calls this directly we refuse to proceed in dev.
  if (!app.isPackaged) return
  /*
   * macOS updates require a code-signed app — Squirrel.Mac refuses to
   * install an unsigned bundle, and electron-updater surfaces that as a
   * cryptic "code signature" error AFTER downloading. The mac build is
   * unsigned for now (no Apple developer account), so rather than fail
   * late every six hours, do not offer updates there at all; the release
   * page is one click away under Help. Remove this once builds are signed.
   */
  if (process.platform === 'darwin') return

  // No surprise downloads — we prompt the user explicitly before pulling
  // bytes so people on metered connections don't get ambushed. Install on
  // quit is safe because it only fires AFTER a successful download that
  // the user agreed to.
  autoUpdater.autoDownload = false
  autoUpdater.autoInstallOnAppQuit = true

  autoUpdater.on('checking-for-update', () => {
    sendStatus(win, { state: 'checking' })
  })

  autoUpdater.on('update-available', (info: UpdateInfo) => {
    sendStatus(win, {
      state: 'available',
      version: info.version,
      releaseNotes: normalizeReleaseNotes(info.releaseNotes)
    })
  })

  autoUpdater.on('update-not-available', (info: UpdateInfo) => {
    sendStatus(win, { state: 'none', version: info?.version ?? null })
  })

  autoUpdater.on('error', (err: Error) => {
    /*
     * electron-updater's messages are written for its own developers: a
     * private repo or a repo with no releases yet comes back as
     * `HttpError: 404 ... Please double check that your authentication
     * token is correct`, which sends a user looking for a token they never
     * had. Translate the cases we can name; pass the rest through.
     */
    const raw = err?.message || String(err)
    let message: string
    if (/404/.test(raw)) {
      message = 'No releases are published yet — check again after the first public release.'
    } else if (/ENOTFOUND|ECONNREFUSED|EAI_AGAIN|net::ERR_INTERNET_DISCONNECTED/i.test(raw)) {
      message = 'Could not reach GitHub — are you offline?'
    } else if (/latest\.yml|app-update\.yml/i.test(raw)) {
      message = 'This build was not published with update metadata.'
    } else {
      message = raw.split('\n')[0].slice(0, 200)
    }
    sendStatus(win, { state: 'error', message })
  })

  autoUpdater.on('download-progress', (p: ProgressInfo) => {
    sendProgress(win, {
      percent: p.percent,
      bytesPerSecond: p.bytesPerSecond,
      transferred: p.transferred,
      total: p.total
    })
  })

  autoUpdater.on('update-downloaded', (info: UpdateInfo) => {
    sendStatus(win, { state: 'downloaded', version: info.version })
  })

  if (!handlersRegistered) {
    ipcMain.handle('update:check', async () => {
      await autoUpdater.checkForUpdates()
    })
    ipcMain.handle('update:download', async () => {
      await autoUpdater.downloadUpdate()
    })
    ipcMain.handle('update:install', () => {
      // quitAndInstall triggers a full app exit, so nothing after this runs.
      autoUpdater.quitAndInstall()
    })
    handlersRegistered = true
  }

  // Kick off the first check shortly after the window becomes visible so we
  // don't compete with first-paint work. `checkForUpdates` returns a promise
  // that rejects on network errors; we funnel those through the `error`
  // event already registered above, so swallow here.
  const firstCheckTimer = setTimeout(() => {
    autoUpdater.checkForUpdates().catch(() => {
      /* surfaced via the 'error' event above */
    })
  }, FIRST_CHECK_DELAY_MS)

  const recheckTimer = setInterval(() => {
    autoUpdater.checkForUpdates().catch(() => {
      /* idem */
    })
  }, RECHECK_INTERVAL_MS)

  win.on('closed', () => {
    clearTimeout(firstCheckTimer)
    clearInterval(recheckTimer)
  })
}
