// Auto-generated by Daisypatcher (C3 SuperMini target)
// Patch: preset-recall
// Target: preset_recall
// DO NOT EDIT — regenerate from the .dpatch file

#include <Arduino.h>
#include <Wire.h>
#include <driver/i2s.h>
#include <math.h>

static const int SAMPLE_RATE = 48000;
static const int BLOCK = 48;
static const i2s_port_t I2S_PORT = I2S_NUM_0;

/*
 * DaisySP's SoftLimit/SoftClip, transliterated.
 *
 * ESP32 builds do not link DaisySP, so any emitter that needs to match a
 * DaisySP-shaped curve has to carry its own copy. Kept here rather than
 * inside one emitter's output because more than one node saturates, and
 * three private copies of the same polynomial is how the two targets
 * drifted apart in the first place.
 */
static inline float dp_soft_clip(float x) {
    if (x < -3.f) return -1.f;
    if (x > 3.f) return 1.f;
    return x * (27.f + x * x) / (27.f + 9.f * x * x);
}
int16_t audio_out_buffer[48 * 2];

// --- Node declarations ---
// Params driven live by a menu leaf (see menuCodegen.ts).
float dp_mp_oscillator_osc1_frequency = 220.f;
float dp_mp_oscillator_osc1_amplitude = 0.4f;
float dp_mp_filter_svf_flt1_frequency = 900.f;
float dp_mp_filter_svf_flt1_resonance = 0.25f;
// --- Presets (see presetCodegen.ts) ---
#define DP_PRESET_COUNT_OK 1
static const int DP_PRESET_COUNT = 3;
static const int DP_PRESET_PARAMS = 4;
// preset 0: Bright
// preset 1: Dark
// preset 2: Mid
static const float dp_preset_table[DP_PRESET_COUNT][DP_PRESET_PARAMS] = {
    { 220.f, 0.4f, 6000.f, 0.15f },
    { 110.f, 0.5f, 240.f, 0.7f },
    { 165.f, 0.45f, 1200.f, 0.4f }
};
static float* const dp_preset_slots[DP_PRESET_PARAMS] = {
    &dp_mp_oscillator_osc1_frequency,
    &dp_mp_oscillator_osc1_amplitude,
    &dp_mp_filter_svf_flt1_frequency,
    &dp_mp_filter_svf_flt1_resonance
};

static inline void dp_preset_apply(int idx) {
    if (idx < 0) idx = 0;
    if (idx >= DP_PRESET_COUNT) idx = DP_PRESET_COUNT - 1;
    for (int i = 0; i < DP_PRESET_PARAMS; i++) {
        *dp_preset_slots[i] = dp_preset_table[idx][i];
    }
}

/* Linear interpolation between two presets. Numeric params only — see the
   header note on why enums cannot come along. */
static inline void dp_preset_morph(int a, int b, float t) {
    if (a < 0) a = 0;
    if (a >= DP_PRESET_COUNT) a = DP_PRESET_COUNT - 1;
    if (b < 0) b = 0;
    if (b >= DP_PRESET_COUNT) b = DP_PRESET_COUNT - 1;
    if (t < 0.f) t = 0.f;
    if (t > 1.f) t = 1.f;
    for (int i = 0; i < DP_PRESET_PARAMS; i++) {
        const float va = dp_preset_table[a][i];
        const float vb = dp_preset_table[b][i];
        *dp_preset_slots[i] = va + (vb - va) * t;
    }
}
// oscillator osc1
float oscillator_osc1_phase = 0.f;
// filter_svf flt1
float filter_svf_flt1_lpS = 0.f; float filter_svf_flt1_bpS = 0.f;
// clock clk1
float clock_clk1_phase = 0.f;

// --- Hardware state ---
// (no hardware components placed)

static inline void render_block() {
    for (int i = 0; i < BLOCK; i++) {
        float in_l = 0.f, in_r = 0.f;
        (void)in_l; (void)in_r;

    {
        float _f = dp_mp_oscillator_osc1_frequency * powf(2.f, 0.f);
        oscillator_osc1_phase += _f / (float)SAMPLE_RATE;
        if (oscillator_osc1_phase >= 1.f) oscillator_osc1_phase -= 1.f;
        if (oscillator_osc1_phase < 0.f) oscillator_osc1_phase += 1.f;
    }
    float oscillator_osc1_out = (2.f * oscillator_osc1_phase - 1.f) * dp_mp_oscillator_osc1_amplitude * 1.f;

    float filter_svf_flt1_lp, filter_svf_flt1_hp, filter_svf_flt1_bp, filter_svf_flt1_notch;
    {
        float _maxF = (float)SAMPLE_RATE * 0.45f;
        float _fc = (dp_mp_filter_svf_flt1_frequency) * powf(2.f, 0.f);
        if (_fc < 20.f) _fc = 20.f; else if (_fc > _maxF) _fc = _maxF;
        float _f = 2.f * sinf(3.14159265f * _fc / (float)SAMPLE_RATE);
        float _r = (dp_mp_filter_svf_flt1_resonance); if (_r < 0.f) _r = 0.f; else if (_r > 1.f) _r = 1.f;
        float _damp = 2.f * (1.f - _r);
        float _x = (oscillator_osc1_out);
        float _hpV = _x - filter_svf_flt1_lpS - _damp * filter_svf_flt1_bpS;
        filter_svf_flt1_bpS += _f * _hpV;
        filter_svf_flt1_lpS += _f * filter_svf_flt1_bpS;
        if (filter_svf_flt1_lpS > 100.f || filter_svf_flt1_lpS < -100.f) filter_svf_flt1_lpS = 0.f;
        if (filter_svf_flt1_bpS > 100.f || filter_svf_flt1_bpS < -100.f) filter_svf_flt1_bpS = 0.f;
        filter_svf_flt1_lp = filter_svf_flt1_lpS; filter_svf_flt1_hp = _hpV; filter_svf_flt1_bp = filter_svf_flt1_bpS; filter_svf_flt1_notch = _hpV + filter_svf_flt1_lpS;
    }

    clock_clk1_phase += ((96.f) / 60.f) / (float)SAMPLE_RATE;
    if (clock_clk1_phase >= 1.f) clock_clk1_phase -= 1.f;
    float clock_clk1_out = (clock_clk1_phase < 0.1f) ? 1.f : 0.f;

    static float preset_recall_pre1_prev = 0.f;
    float preset_recall_pre1_t = clock_clk1_out;
    bool preset_recall_pre1_edge = (preset_recall_pre1_t >= 0.5f) && (preset_recall_pre1_prev < 0.5f);
    preset_recall_pre1_prev = preset_recall_pre1_t;
#ifdef DP_PRESET_COUNT_OK
    if (preset_recall_pre1_edge) dp_preset_apply((int)(1.f));
#endif
    float preset_recall_pre1_changed = preset_recall_pre1_edge ? 1.f : 0.f;

        float out_l = filter_svf_flt1_lp;
        float out_r = filter_svf_flt1_lp;
        audio_out_buffer[i*2]     = (int16_t)(fmaxf(-1.f, fminf(1.f, out_l)) * 32767.f);
        audio_out_buffer[i*2 + 1] = (int16_t)(fmaxf(-1.f, fminf(1.f, out_r)) * 32767.f);
    }
}

void setup() {
    Serial.begin(115200);

    // --- Hardware pin setup ---
    // (no hardware init)

    // --- Node init ---


    // --- I2S audio out ---
    i2s_config_t i2s_cfg = {
        .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_TX),
        .sample_rate = SAMPLE_RATE,
        .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
        .channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT,
        .communication_format = I2S_COMM_FORMAT_STAND_I2S,
        .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,
        .dma_buf_count = 4,
        .dma_buf_len = 48,
        .use_apll = false,
        .tx_desc_auto_clear = true,
        .fixed_mclk = 0
    };
    i2s_pin_config_t pin_cfg = {
        .bck_io_num = 4,
        .ws_io_num = 5,
        .data_out_num = 6,
        .data_in_num = I2S_PIN_NO_CHANGE
    };
    i2s_driver_install(I2S_PORT, &i2s_cfg, 0, nullptr);
    i2s_set_pin(I2S_PORT, &pin_cfg);
    i2s_set_clk(I2S_PORT, SAMPLE_RATE, I2S_BITS_PER_SAMPLE_16BIT, I2S_CHANNEL_STEREO);
}

void loop() {
    // --- Poll hardware (ADC + GPIO) ---
    // (no hardware inputs)

    // --- Slow peripherals (I2C sensors etc). NEVER inside render_block(). ---
    // (none)

    // --- Copy bound hardware values into per-node state ---
    // (no bindings)

    // --- Render one audio block + push to I2S ---
    render_block();
    size_t written = 0;
    i2s_write(I2S_PORT, audio_out_buffer, sizeof(audio_out_buffer), &written, portMAX_DELAY);
}
