// Auto-generated by Daisypatcher
// Patch: drums_kit
// Target: drums_kit
// DO NOT EDIT — regenerate from the .dpatch file

#include "daisy_seed.h"
#include "daisysp.h"
#include <cmath>
#include <cstdlib>

using namespace daisy;
using namespace daisysp;

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// Maximum delay-line length (samples). Enough for 2s at 48kHz.
static constexpr size_t CODEGEN_MAX_DELAY = static_cast<size_t>(48000 * 2);

DaisySeed hw;

// --- Node declarations ---
// clock clk1
float clock_clk1_phase = 0.f;
// drum_kick kick1
AnalogBassDrum drum_kick_kick1;
// drum_snare snare1
AnalogSnareDrum drum_snare_snare1;
// drum_hat hat1
HiHat<> drum_hat_hat1;

void AudioCallback(AudioHandle::InputBuffer in,
                   AudioHandle::OutputBuffer out,
                   size_t size) {
    float sr = hw.AudioSampleRate();
    for (size_t i = 0; i < size; i++) {
        float in_l = in[0][i];
        float in_r = in[1][i];
        (void)in_l; (void)in_r; (void)sr;

    clock_clk1_phase += ((120.f) / 60.f) / sr;
    if (clock_clk1_phase >= 1.f) clock_clk1_phase -= 1.f;
    float clock_clk1_out = (clock_clk1_phase < 0.1f) ? 1.f : 0.f;

    static float drum_kick_kick1_prev_trig = 0.f;
    drum_kick_kick1.SetFreq(60.f);
    drum_kick_kick1.SetDecay(0.35f);
    drum_kick_kick1.SetAttackFmAmount(0.5f);
    float drum_kick_kick1_tin = clock_clk1_out;
    bool drum_kick_kick1_edge = (drum_kick_kick1_tin >= 0.5f) && (drum_kick_kick1_prev_trig < 0.5f);
    drum_kick_kick1_prev_trig = drum_kick_kick1_tin;
    if (drum_kick_kick1_edge) drum_kick_kick1.Trig();
    float drum_kick_kick1_out = drum_kick_kick1.Process(false);

    static float drum_snare_snare1_prev_trig = 0.f;
    drum_snare_snare1.SetFreq(200.f);
    drum_snare_snare1.SetDecay(0.2f);
    drum_snare_snare1.SetSnappy(0.5f);
    float drum_snare_snare1_tin = clock_clk1_out;
    bool drum_snare_snare1_edge = (drum_snare_snare1_tin >= 0.5f) && (drum_snare_snare1_prev_trig < 0.5f);
    drum_snare_snare1_prev_trig = drum_snare_snare1_tin;
    if (drum_snare_snare1_edge) drum_snare_snare1.Trig();
    float drum_snare_snare1_out = drum_snare_snare1.Process(false);

    static float drum_hat_hat1_prev_trig = 0.f;
    drum_hat_hat1.SetDecay(0.08f);
    drum_hat_hat1.SetTone(0.7f);
    float drum_hat_hat1_tin = clock_clk1_out;
    bool drum_hat_hat1_edge = (drum_hat_hat1_tin >= 0.5f) && (drum_hat_hat1_prev_trig < 0.5f);
    drum_hat_hat1_prev_trig = drum_hat_hat1_tin;
    if (drum_hat_hat1_edge) drum_hat_hat1.Trig();
    float drum_hat_hat1_out = drum_hat_hat1.Process(false);

    float mixer4_mix1_out = (drum_kick_kick1_out) * (1.f) + (drum_snare_snare1_out) * (1.f) + (drum_hat_hat1_out) * (1.f) + (0.f) * (1.f);

        float out_l = mixer4_mix1_out;
        float out_r = mixer4_mix1_out;
        out[0][i] = out_l;
        out[1][i] = out_r;
    }
}

int main(void) {
    // boost=true moves the H7 to 480MHz so the SAI MCLK ratio lands cleanly
    // on the AK4556's expected bit-clock. Without it the codec DAC can end
    // up silent or VERY quiet even though the callback runs — validated
    // with an LED-in-callback test on 2026-04-21.
    hw.Init(true);
    hw.SetAudioBlockSize(48);
    float sr = hw.AudioSampleRate();
    (void)sr;

    drum_kick_kick1.Init(sr);
    drum_kick_kick1.SetFreq(60.f);
    drum_kick_kick1.SetDecay(0.35f);
    drum_kick_kick1.SetAttackFmAmount(0.5f);
    drum_snare_snare1.Init(sr);
    drum_snare_snare1.SetFreq(200.f);
    drum_snare_snare1.SetDecay(0.2f);
    drum_snare_snare1.SetSnappy(0.5f);
    drum_hat_hat1.Init(sr);
    drum_hat_hat1.SetDecay(0.08f);
    drum_hat_hat1.SetTone(0.7f);



    hw.StartAudio(AudioCallback);

    while (1) {

        System::Delay(1);
    }
}
