// Auto-generated by Daisypatcher
// Patch: delay_reverb_chain
// Target: delay_reverb_chain
// DO NOT EDIT — regenerate from the .dpatch file

#include "daisy_seed.h"
#include "daisysp.h"
#include <cmath>
#include <cstdlib>

using namespace daisy;
using namespace daisysp;

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// Maximum delay-line length (samples). Enough for 2s at 48kHz.
static constexpr size_t CODEGEN_MAX_DELAY = static_cast<size_t>(48000 * 2);

DaisySeed hw;

// --- Node declarations ---
// oscillator osc1
Oscillator oscillator_osc1;
// delay dly1
DelayLine<float, CODEGEN_MAX_DELAY> delay_dly1 DSY_SDRAM_BSS;
// reverb rev1
ReverbSc reverb_rev1;

void AudioCallback(AudioHandle::InputBuffer in,
                   AudioHandle::OutputBuffer out,
                   size_t size) {
    float sr = hw.AudioSampleRate();
    for (size_t i = 0; i < size; i++) {
        float in_l = in[0][i];
        float in_r = in[1][i];
        (void)in_l; (void)in_r; (void)sr;

    oscillator_osc1.SetFreq(220.f * powf(2.f, 0.f));
    oscillator_osc1.SetAmp(0.5f * 1.f);
    float oscillator_osc1_out = oscillator_osc1.Process();

    delay_dly1.SetDelay(fmaxf(1.f, fminf((float)CODEGEN_MAX_DELAY - 1.f, ((0.25f + (0.f))) * sr)));
    float delay_dly1_r = delay_dly1.Read();
    delay_dly1.Write((oscillator_osc1_out) + delay_dly1_r * (0.4f));
    float delay_dly1_out = (oscillator_osc1_out) * (1.f - (0.5f)) + delay_dly1_r * (0.5f);

    reverb_rev1.SetFeedback(0.5f + (0.5f) * 0.45f);
    reverb_rev1.SetLpFreq(1000.f + (1.f - (0.5f)) * 15000.f);
    float reverb_rev1_wl = 0.f, reverb_rev1_wr = 0.f;
    reverb_rev1.Process(delay_dly1_out, delay_dly1_out, &reverb_rev1_wl, &reverb_rev1_wr);
    float reverb_rev1_out = (delay_dly1_out) * (1.f - (0.3f)) + 0.5f * (reverb_rev1_wl + reverb_rev1_wr) * (0.3f);

        float out_l = reverb_rev1_out;
        float out_r = reverb_rev1_out;
        out[0][i] = out_l;
        out[1][i] = out_r;
    }
}

int main(void) {
    // boost=true moves the H7 to 480MHz so the SAI MCLK ratio lands cleanly
    // on the AK4556's expected bit-clock. Without it the codec DAC can end
    // up silent or VERY quiet even though the callback runs — validated
    // with an LED-in-callback test on 2026-04-21.
    hw.Init(true);
    hw.SetAudioBlockSize(48);
    float sr = hw.AudioSampleRate();
    (void)sr;

    oscillator_osc1.Init(sr);
    oscillator_osc1.SetWaveform(Oscillator::WAVE_SIN);
    oscillator_osc1.SetFreq(220.f);
    oscillator_osc1.SetAmp(0.5f);
    delay_dly1.Init();
    delay_dly1.SetDelay(0.25f * sr);
    // ReverbSc requires USE_DAISYSP_LGPL=1 in the Makefile.
    reverb_rev1.Init(sr);
    reverb_rev1.SetFeedback(0.5f + 0.5f * 0.45f);
    reverb_rev1.SetLpFreq(1000.f + (1.f - 0.5f) * 15000.f);



    hw.StartAudio(AudioCallback);

    while (1) {

        System::Delay(1);
    }
}
