// Auto-generated by Daisypatcher
// Patch: karplus_seq
// Target: karplus_seq
// DO NOT EDIT — regenerate from the .dpatch file

#include "daisy_seed.h"
#include "daisysp.h"
#include <cmath>
#include <cstdlib>

using namespace daisy;
using namespace daisysp;

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// Maximum delay-line length (samples). Enough for 2s at 48kHz.
static constexpr size_t CODEGEN_MAX_DELAY = static_cast<size_t>(48000 * 2);

DaisySeed hw;

// --- Node declarations ---
// clock clk1
float clock_clk1_phase = 0.f;
// step_seq seq1
uint32_t step_seq_seq1_step = 0;
float step_seq_seq1_prev_clk = 0.f;
float step_seq_seq1_prev_rst = 0.f;
// karplus kp1
String karplus_kp1;
Random karplus_kp1_rng;

void AudioCallback(AudioHandle::InputBuffer in,
                   AudioHandle::OutputBuffer out,
                   size_t size) {
    float sr = hw.AudioSampleRate();
    for (size_t i = 0; i < size; i++) {
        float in_l = in[0][i];
        float in_r = in[1][i];
        (void)in_l; (void)in_r; (void)sr;

    clock_clk1_phase += ((120.f) / 60.f) / sr;
    if (clock_clk1_phase >= 1.f) clock_clk1_phase -= 1.f;
    float clock_clk1_out = (clock_clk1_phase < 0.1f) ? 1.f : 0.f;

    static const float step_seq_seq1_steps[8] = { 0.f, 0.2f, 0.4f, 0.1f, 0.f, 0.f, 0.f, 0.f };
    static const float step_seq_seq1_gates[8] = { 1.f, 1.f, 1.f, 1.f, 0.f, 0.f, 0.f, 0.f };
    {
        float ci = clock_clk1_out;
        float ri = 0.f;
        if (ri > 0.5f && step_seq_seq1_prev_rst <= 0.5f) {
            step_seq_seq1_step = 0;
        } else if (ci > 0.5f && step_seq_seq1_prev_clk <= 0.5f) {
            step_seq_seq1_step = (step_seq_seq1_step + 1u) & 7u;
        }
        step_seq_seq1_prev_rst = ri;
        step_seq_seq1_prev_clk = ci;
    }
    float step_seq_seq1_cv = step_seq_seq1_steps[step_seq_seq1_step];
    float step_seq_seq1_gate = step_seq_seq1_gates[step_seq_seq1_step] * ((clock_clk1_out) > 0.5f ? 1.f : 0.f);

    static float karplus_kp1_prev_trig = 0.f;
    karplus_kp1.SetFreq(fmaxf(50.f, fminf(2000.f, step_seq_seq1_cv)));
    karplus_kp1.SetBrightness(0.99f);
    karplus_kp1.SetDamping(0.5f);
    float karplus_kp1_trig_in = step_seq_seq1_gate;
    bool karplus_kp1_edge = (karplus_kp1_trig_in > 0.5f) && (karplus_kp1_prev_trig <= 0.5f);
    karplus_kp1_prev_trig = karplus_kp1_trig_in;
    static int karplus_kp1_burst = 0;
    if (karplus_kp1_edge) karplus_kp1_burst = (int)(sr / fmaxf(50.f, fmaxf(50.f, fminf(2000.f, step_seq_seq1_cv))));
    float karplus_kp1_exc = 0.f;
    if (karplus_kp1_burst > 0) { karplus_kp1_exc = karplus_kp1_rng.GetFloat(-1.f, 1.f); karplus_kp1_burst--; }
    float karplus_kp1_out = karplus_kp1.Process(karplus_kp1_exc);

        float out_l = karplus_kp1_out;
        float out_r = karplus_kp1_out;
        out[0][i] = out_l;
        out[1][i] = out_r;
    }
}

int main(void) {
    // boost=true moves the H7 to 480MHz so the SAI MCLK ratio lands cleanly
    // on the AK4556's expected bit-clock. Without it the codec DAC can end
    // up silent or VERY quiet even though the callback runs — validated
    // with an LED-in-callback test on 2026-04-21.
    hw.Init(true);
    hw.SetAudioBlockSize(48);
    float sr = hw.AudioSampleRate();
    (void)sr;

    karplus_kp1.Init(sr);
    karplus_kp1.SetFreq(220.f);
    karplus_kp1.SetDamping(0.5f);
    karplus_kp1.SetNonLinearity(0.1f);
    karplus_kp1.SetBrightness(0.99f);



    hw.StartAudio(AudioCallback);

    while (1) {

        System::Delay(1);
    }
}
