// Auto-generated by Daisypatcher (ESP32-S3 target)
// Patch: delay_reverb_chain
// Target: delay_reverb_chain
// DO NOT EDIT — regenerate from the .dpatch file

#include <Arduino.h>
#include <Wire.h>
#include <driver/i2s.h>
#include <math.h>

static const int SAMPLE_RATE = 48000;
static const int BLOCK = 48;
static const i2s_port_t I2S_PORT = I2S_NUM_0;

/*
 * DaisySP's SoftLimit/SoftClip, transliterated.
 *
 * ESP32 builds do not link DaisySP, so any emitter that needs to match a
 * DaisySP-shaped curve has to carry its own copy. Kept here rather than
 * inside one emitter's output because more than one node saturates, and
 * three private copies of the same polynomial is how the two targets
 * drifted apart in the first place.
 */
static inline float dp_soft_clip(float x) {
    if (x < -3.f) return -1.f;
    if (x > 3.f) return 1.f;
    return x * (27.f + x * x) / (27.f + 9.f * x * x);
}
int16_t audio_out_buffer[48 * 2];

// --- Node declarations ---
// oscillator osc1
float oscillator_osc1_phase = 0.f;
// delay dly1
static constexpr int delay_dly1_LEN = 12002;
static float delay_dly1_buf[delay_dly1_LEN] = {0}; int delay_dly1_idx = 0;
// reverb rev1
static const int reverb_rev1_comb_maxlen[8] = { 1214, 1293, 1389, 1475, 1547, 1622, 1694, 1759 };
static const int reverb_rev1_ap_maxlen[4] = { 605, 480, 371, 245 };
static float reverb_rev1_comb_buf[8][1760] = {{0}};
static int reverb_rev1_comb_idx[8] = {0};
static int reverb_rev1_comb_len[8] = {0};
static float reverb_rev1_comb_store[8] = {0};
static float reverb_rev1_ap_buf[4][608] = {{0}};
static int reverb_rev1_ap_idx[4] = {0};
static int reverb_rev1_ap_len[4] = {0};

// --- Hardware state ---
// (no hardware components placed)

static inline void render_block() {
    for (int i = 0; i < BLOCK; i++) {
        float in_l = 0.f, in_r = 0.f;
        (void)in_l; (void)in_r;

    {
        float _f = 220.f * powf(2.f, 0.f);
        oscillator_osc1_phase += _f / (float)SAMPLE_RATE;
        if (oscillator_osc1_phase >= 1.f) oscillator_osc1_phase -= 1.f;
        if (oscillator_osc1_phase < 0.f) oscillator_osc1_phase += 1.f;
    }
    float oscillator_osc1_out = sinf(oscillator_osc1_phase * 6.28318530718f) * 0.5f * 1.f;

    float delay_dly1_out;
    {
        int _len = (int)((0.25f) * (float)SAMPLE_RATE); if (_len < 1) _len = 1; if (_len > delay_dly1_LEN) _len = delay_dly1_LEN;
        int _ri = delay_dly1_idx - _len; if (_ri < 0) _ri += delay_dly1_LEN;
        float _wet = delay_dly1_buf[_ri];
        float _in = (oscillator_osc1_out);
        delay_dly1_buf[delay_dly1_idx] = _in + _wet * (0.4f);
        delay_dly1_idx = (delay_dly1_idx + 1) % delay_dly1_LEN;
        delay_dly1_out = _in * (1.f - (0.5f)) + _wet * (0.5f);
    }

    float reverb_rev1_out;
    {
        float _size = (0.5f); if (_size < 0.f) _size = 0.f; else if (_size > 1.f) _size = 1.f;
        float _damp = (0.5f); if (_damp < 0.f) _damp = 0.f; else if (_damp > 1.f) _damp = 1.f;
        float _m = (0.3f); if (_m < 0.f) _m = 0.f; else if (_m > 1.f) _m = 1.f;
        float _roomsize = _size * 0.28f + 0.7f;
        float _d1 = _damp * 0.4f;
        float _d2 = 1.f - _d1;
        float _dry = (delay_dly1_out);
        float _in = _dry * 0.015f;
        float _wet = 0.f;
        for (int _k = 0; _k < 8; _k++) {
            int _idx = reverb_rev1_comb_idx[_k];
            float _o = reverb_rev1_comb_buf[_k][_idx];
            reverb_rev1_comb_store[_k] = _o * _d2 + reverb_rev1_comb_store[_k] * _d1;
            reverb_rev1_comb_buf[_k][_idx] = _in + reverb_rev1_comb_store[_k] * _roomsize;
            _idx++; if (_idx >= reverb_rev1_comb_len[_k]) _idx = 0;
            reverb_rev1_comb_idx[_k] = _idx;
            _wet += _o;
        }
        for (int _k = 0; _k < 4; _k++) {
            int _idx = reverb_rev1_ap_idx[_k];
            float _bo = reverb_rev1_ap_buf[_k][_idx];
            float _o = -_wet + _bo;
            reverb_rev1_ap_buf[_k][_idx] = _wet + _bo * 0.5f;
            _idx++; if (_idx >= reverb_rev1_ap_len[_k]) _idx = 0;
            reverb_rev1_ap_idx[_k] = _idx;
            _wet = _o;
        }
        reverb_rev1_out = _dry * (1.f - _m) + _wet * _m;
    }

        float out_l = reverb_rev1_out;
        float out_r = reverb_rev1_out;
        audio_out_buffer[i*2]     = (int16_t)(fmaxf(-1.f, fminf(1.f, out_l)) * 32767.f);
        audio_out_buffer[i*2 + 1] = (int16_t)(fmaxf(-1.f, fminf(1.f, out_r)) * 32767.f);
    }
}

void setup() {
    Serial.begin(115200);

    // --- Hardware pin setup ---
    // (no hardware init)

    // --- Node init ---
    {
        static const int _comb_44k[8] = { 1116, 1188, 1277, 1356, 1422, 1491, 1557, 1617 };
        static const int _ap_44k[4] = { 556, 441, 341, 225 };
        float _scale = (float)SAMPLE_RATE / 44100.f;
        for (int _k = 0; _k < 8; _k++) {
            int _dlen = (int)((float)_comb_44k[_k] * _scale + 0.5f);
            if (_dlen < 1) _dlen = 1;
            if (_dlen > reverb_rev1_comb_maxlen[_k]) _dlen = reverb_rev1_comb_maxlen[_k];
            reverb_rev1_comb_len[_k] = _dlen;
        }
        for (int _k = 0; _k < 4; _k++) {
            int _dlen = (int)((float)_ap_44k[_k] * _scale + 0.5f);
            if (_dlen < 1) _dlen = 1;
            if (_dlen > reverb_rev1_ap_maxlen[_k]) _dlen = reverb_rev1_ap_maxlen[_k];
            reverb_rev1_ap_len[_k] = _dlen;
        }
    }

    // --- I2S audio out ---
    i2s_config_t i2s_cfg = {
        .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_TX),
        .sample_rate = SAMPLE_RATE,
        .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
        .channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT,
        .communication_format = I2S_COMM_FORMAT_STAND_I2S,
        .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,
        .dma_buf_count = 4,
        .dma_buf_len = 48,
        .use_apll = false,
        .tx_desc_auto_clear = true,
        .fixed_mclk = 0
    };
    i2s_pin_config_t pin_cfg = {
        .bck_io_num = 36,
        .ws_io_num = 37,
        .data_out_num = 35,
        .data_in_num = I2S_PIN_NO_CHANGE
    };
    i2s_driver_install(I2S_PORT, &i2s_cfg, 0, nullptr);
    i2s_set_pin(I2S_PORT, &pin_cfg);
    i2s_set_clk(I2S_PORT, SAMPLE_RATE, I2S_BITS_PER_SAMPLE_16BIT, I2S_CHANNEL_STEREO);
}

void loop() {
    // --- Poll hardware (ADC + GPIO) ---
    // (no hardware inputs)

    // --- Slow peripherals (I2C sensors etc). NEVER inside render_block(). ---
    // (none)

    // --- Copy bound hardware values into per-node state ---
    // (no bindings)

    // --- Render one audio block + push to I2S ---
    render_block();
    size_t written = 0;
    i2s_write(I2S_PORT, audio_out_buffer, sizeof(audio_out_buffer), &written, portMAX_DELAY);
}
