// Auto-generated by Daisypatcher
// Patch: granulator_freeze
// Target: granulator_freeze
// DO NOT EDIT — regenerate from the .dpatch file

#include "daisy_seed.h"
#include "daisysp.h"
#include <cmath>
#include <cstdlib>

using namespace daisy;
using namespace daisysp;

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// Maximum delay-line length (samples). Enough for 2s at 48kHz.
static constexpr size_t CODEGEN_MAX_DELAY = static_cast<size_t>(48000 * 2);

DaisySeed hw;

// --- Node declarations ---
// oscillator osc1
Oscillator oscillator_osc1;
// granulator gran1
constexpr size_t granulator_gran1_BUF = 192000;
constexpr size_t granulator_gran1_MAX_GRAINS = 8;
float granulator_gran1_buf[granulator_gran1_BUF] DSY_SDRAM_BSS;
size_t granulator_gran1_w = 0;
float granulator_gran1_spawn_cd = 0.f;
uint32_t granulator_gran1_rng_state = 0x9e3779b9u;
struct granulator_gran1_Grain {
    bool  active;
    float pos;
    float start;
    float len;
    float rate;
};
granulator_gran1_Grain granulator_gran1_grains[granulator_gran1_MAX_GRAINS] = {};
// clock clk1
float clock_clk1_phase = 0.f;
// freeze frz1
static constexpr size_t freeze_frz1_SIZE = 48000;
float freeze_frz1_buf[freeze_frz1_SIZE] DSY_SDRAM_BSS;
size_t freeze_frz1_w = 0;
size_t freeze_frz1_r = 0;
bool freeze_frz1_frozen = false;
float freeze_frz1_prev_gate = 0.f;

void AudioCallback(AudioHandle::InputBuffer in,
                   AudioHandle::OutputBuffer out,
                   size_t size) {
    float sr = hw.AudioSampleRate();
    for (size_t i = 0; i < size; i++) {
        float in_l = in[0][i];
        float in_r = in[1][i];
        (void)in_l; (void)in_r; (void)sr;

    oscillator_osc1.SetFreq(220.f * powf(2.f, 0.f));
    oscillator_osc1.SetAmp(0.5f * 1.f);
    float oscillator_osc1_out = oscillator_osc1.Process();

    float granulator_gran1_out;
    {
        const float TWO_PI = 2.f * (float)M_PI;
        float x = oscillator_osc1_out;
        // write into circular buffer
        granulator_gran1_buf[granulator_gran1_w] = x;
        granulator_gran1_w = (granulator_gran1_w + 1) % granulator_gran1_BUF;
        float _jitter = (0.3f);
        float grainSamples = ((80.f) * 0.001f) * sr;
        if (grainSamples < 1.f) grainSamples = 1.f;
        float spawnInterval = sr / (((8.f)) > 0.001f ? ((8.f)) : 0.001f);
        granulator_gran1_spawn_cd -= 1.f;
        if (granulator_gran1_spawn_cd <= 0.f) {
            // xorshift32 for cheap PRNG — not calling daisy::Random here
            // because grain spawn runs at audio rate.
            granulator_gran1_rng_state ^= granulator_gran1_rng_state << 13;
            granulator_gran1_rng_state ^= granulator_gran1_rng_state >> 17;
            granulator_gran1_rng_state ^= granulator_gran1_rng_state << 5;
            float r0 = (float)granulator_gran1_rng_state * (1.f / 4294967296.f); // [0,1)
            granulator_gran1_rng_state ^= granulator_gran1_rng_state << 13;
            granulator_gran1_rng_state ^= granulator_gran1_rng_state >> 17;
            granulator_gran1_rng_state ^= granulator_gran1_rng_state << 5;
            float r1 = (float)granulator_gran1_rng_state * (1.f / 4294967296.f);
            int slot = -1;
            for (int s = 0; s < (int)granulator_gran1_MAX_GRAINS; s++) {
                if (!granulator_gran1_grains[s].active) { slot = s; break; }
            }
            if (slot >= 0) {
                float jit = (r0 * 2.f - 1.f) * _jitter;
                float back = grainSamples * (1.f + 2.f * _jitter) + r1 * _jitter * (float)(granulator_gran1_BUF - (size_t)grainSamples - 2);
                float start = (float)granulator_gran1_w - grainSamples - back;
                while (start < 0.f) start += (float)granulator_gran1_BUF;
                while (start >= (float)granulator_gran1_BUF) start -= (float)granulator_gran1_BUF;
                float pitchJit = (0.f) + jit * 2.f;
                float rate = powf(2.f, pitchJit / 12.f);
                granulator_gran1_grains[slot].active = true;
                granulator_gran1_grains[slot].pos = 0.f;
                granulator_gran1_grains[slot].start = start;
                granulator_gran1_grains[slot].len = grainSamples;
                granulator_gran1_grains[slot].rate = rate;
            }
            granulator_gran1_spawn_cd += spawnInterval;
        }
        float wet = 0.f;
        for (size_t s = 0; s < granulator_gran1_MAX_GRAINS; s++) {
            if (!granulator_gran1_grains[s].active) continue;
            float pos = granulator_gran1_grains[s].pos;
            float len = granulator_gran1_grains[s].len;
            if (pos >= len) { granulator_gran1_grains[s].active = false; continue; }
            float readPos = granulator_gran1_grains[s].start + pos;
            while (readPos >= (float)granulator_gran1_BUF) readPos -= (float)granulator_gran1_BUF;
            while (readPos < 0.f) readPos += (float)granulator_gran1_BUF;
            size_t ri0 = (size_t)readPos;
            float frac = readPos - (float)ri0;
            size_t ri1 = (ri0 + 1) % granulator_gran1_BUF;
            float sample = granulator_gran1_buf[ri0] * (1.f - frac) + granulator_gran1_buf[ri1] * frac;
            float env = 0.5f - 0.5f * cosf((TWO_PI * pos) / len);
            wet += sample * env;
            granulator_gran1_grains[s].pos = pos + granulator_gran1_grains[s].rate;
        }
        if (!isfinite(wet)) wet = 0.f;
        granulator_gran1_out = x * (1.f - (1.f)) + wet * (1.f);
    }

    clock_clk1_phase += ((120.f) / 60.f) / sr;
    if (clock_clk1_phase >= 1.f) clock_clk1_phase -= 1.f;
    float clock_clk1_out = (clock_clk1_phase < 0.1f) ? 1.f : 0.f;

    float freeze_frz1_out;
    {
        size_t span = (size_t)((120.f) * 0.001f * sr);
        if (span < 1) span = 1;
        if (span >= freeze_frz1_SIZE) span = freeze_frz1_SIZE - 1;
        float gi = clock_clk1_out;
        if (gi > 0.5f && freeze_frz1_prev_gate <= 0.5f) { freeze_frz1_frozen = true; freeze_frz1_r = 0; }
        if (gi <= 0.5f && freeze_frz1_prev_gate > 0.5f) { freeze_frz1_frozen = false; }
        freeze_frz1_prev_gate = gi;
        if (!freeze_frz1_frozen) { freeze_frz1_buf[freeze_frz1_w] = granulator_gran1_out; freeze_frz1_w = (freeze_frz1_w + 1) % span; }
        if (freeze_frz1_frozen) { freeze_frz1_out = freeze_frz1_buf[freeze_frz1_r]; freeze_frz1_r = (freeze_frz1_r + 1) % span; }
        else freeze_frz1_out = granulator_gran1_out;
    }

        float out_l = freeze_frz1_out;
        float out_r = freeze_frz1_out;
        out[0][i] = out_l;
        out[1][i] = out_r;
    }
}

int main(void) {
    // boost=true moves the H7 to 480MHz so the SAI MCLK ratio lands cleanly
    // on the AK4556's expected bit-clock. Without it the codec DAC can end
    // up silent or VERY quiet even though the callback runs — validated
    // with an LED-in-callback test on 2026-04-21.
    hw.Init(true);
    hw.SetAudioBlockSize(48);
    float sr = hw.AudioSampleRate();
    (void)sr;

    oscillator_osc1.Init(sr);
    oscillator_osc1.SetWaveform(Oscillator::WAVE_SIN);
    oscillator_osc1.SetFreq(220.f);
    oscillator_osc1.SetAmp(0.5f);
    for (size_t zi = 0; zi < granulator_gran1_BUF; zi++) granulator_gran1_buf[zi] = 0.f;
    for (size_t gi = 0; gi < granulator_gran1_MAX_GRAINS; gi++) granulator_gran1_grains[gi].active = false;
    for (size_t k = 0; k < freeze_frz1_SIZE; ++k) freeze_frz1_buf[k] = 0.f;



    hw.StartAudio(AudioCallback);

    while (1) {

        System::Delay(1);
    }
}
