// Auto-generated by Daisypatcher (C3 SuperMini target)
// Patch: bare_osc_out
// Target: bare_osc_out
// DO NOT EDIT — regenerate from the .dpatch file

#include <Arduino.h>
#include <Wire.h>
#include <driver/i2s.h>
#include <math.h>

static const int SAMPLE_RATE = 48000;
static const int BLOCK = 48;
static const i2s_port_t I2S_PORT = I2S_NUM_0;

/*
 * DaisySP's SoftLimit/SoftClip, transliterated.
 *
 * ESP32 builds do not link DaisySP, so any emitter that needs to match a
 * DaisySP-shaped curve has to carry its own copy. Kept here rather than
 * inside one emitter's output because more than one node saturates, and
 * three private copies of the same polynomial is how the two targets
 * drifted apart in the first place.
 */
static inline float dp_soft_clip(float x) {
    if (x < -3.f) return -1.f;
    if (x > 3.f) return 1.f;
    return x * (27.f + x * x) / (27.f + 9.f * x * x);
}
int16_t audio_out_buffer[48 * 2];

// --- Node declarations ---
// oscillator osc1
float oscillator_osc1_phase = 0.f;

// --- Hardware state ---
// (no hardware components placed)

static inline void render_block() {
    for (int i = 0; i < BLOCK; i++) {
        float in_l = 0.f, in_r = 0.f;
        (void)in_l; (void)in_r;

    {
        float _f = 220.f * powf(2.f, 0.f);
        oscillator_osc1_phase += _f / (float)SAMPLE_RATE;
        if (oscillator_osc1_phase >= 1.f) oscillator_osc1_phase -= 1.f;
        if (oscillator_osc1_phase < 0.f) oscillator_osc1_phase += 1.f;
    }
    float oscillator_osc1_out = sinf(oscillator_osc1_phase * 6.28318530718f) * 0.5f * 1.f;

        float out_l = oscillator_osc1_out;
        float out_r = oscillator_osc1_out;
        audio_out_buffer[i*2]     = (int16_t)(fmaxf(-1.f, fminf(1.f, out_l)) * 32767.f);
        audio_out_buffer[i*2 + 1] = (int16_t)(fmaxf(-1.f, fminf(1.f, out_r)) * 32767.f);
    }
}

void setup() {
    Serial.begin(115200);

    // --- Hardware pin setup ---
    // (no hardware init)

    // --- Node init ---


    // --- I2S audio out ---
    i2s_config_t i2s_cfg = {
        .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_TX),
        .sample_rate = SAMPLE_RATE,
        .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
        .channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT,
        .communication_format = I2S_COMM_FORMAT_STAND_I2S,
        .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,
        .dma_buf_count = 4,
        .dma_buf_len = 48,
        .use_apll = false,
        .tx_desc_auto_clear = true,
        .fixed_mclk = 0
    };
    i2s_pin_config_t pin_cfg = {
        .bck_io_num = 4,
        .ws_io_num = 5,
        .data_out_num = 6,
        .data_in_num = I2S_PIN_NO_CHANGE
    };
    i2s_driver_install(I2S_PORT, &i2s_cfg, 0, nullptr);
    i2s_set_pin(I2S_PORT, &pin_cfg);
    i2s_set_clk(I2S_PORT, SAMPLE_RATE, I2S_BITS_PER_SAMPLE_16BIT, I2S_CHANNEL_STEREO);
}

void loop() {
    // --- Poll hardware (ADC + GPIO) ---
    // (no hardware inputs)

    // --- Slow peripherals (I2C sensors etc). NEVER inside render_block(). ---
    // (none)

    // --- Copy bound hardware values into per-node state ---
    // (no bindings)

    // --- Render one audio block + push to I2S ---
    render_block();
    size_t written = 0;
    i2s_write(I2S_PORT, audio_out_buffer, sizeof(audio_out_buffer), &written, portMAX_DELAY);
}
