// Auto-generated by Daisypatcher
// Patch: adsr_vca_clock
// Target: adsr_vca_clock
// DO NOT EDIT — regenerate from the .dpatch file

#include "daisy_seed.h"
#include "daisysp.h"
#include <cmath>
#include <cstdlib>

using namespace daisy;
using namespace daisysp;

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// Maximum delay-line length (samples). Enough for 2s at 48kHz.
static constexpr size_t CODEGEN_MAX_DELAY = static_cast<size_t>(48000 * 2);

DaisySeed hw;

// --- Node declarations ---
// clock clk1
float clock_clk1_phase = 0.f;
// adsr adsr1
Adsr adsr_adsr1;
// oscillator osc1
Oscillator oscillator_osc1;

void AudioCallback(AudioHandle::InputBuffer in,
                   AudioHandle::OutputBuffer out,
                   size_t size) {
    float sr = hw.AudioSampleRate();
    for (size_t i = 0; i < size; i++) {
        float in_l = in[0][i];
        float in_r = in[1][i];
        (void)in_l; (void)in_r; (void)sr;

    clock_clk1_phase += ((120.f) / 60.f) / sr;
    if (clock_clk1_phase >= 1.f) clock_clk1_phase -= 1.f;
    float clock_clk1_out = (clock_clk1_phase < 0.1f) ? 1.f : 0.f;

    float adsr_adsr1_out = adsr_adsr1.Process((clock_clk1_out) > 0.5f);

    oscillator_osc1.SetFreq(220.f * powf(2.f, 0.f));
    oscillator_osc1.SetAmp(0.5f * 1.f);
    float oscillator_osc1_out = oscillator_osc1.Process();

    float vca_vca1_out = (oscillator_osc1_out) * ((adsr_adsr1_out) + 0.f);

        float out_l = vca_vca1_out;
        float out_r = vca_vca1_out;
        out[0][i] = out_l;
        out[1][i] = out_r;
    }
}

int main(void) {
    // boost=true moves the H7 to 480MHz so the SAI MCLK ratio lands cleanly
    // on the AK4556's expected bit-clock. Without it the codec DAC can end
    // up silent or VERY quiet even though the callback runs — validated
    // with an LED-in-callback test on 2026-04-21.
    hw.Init(true);
    hw.SetAudioBlockSize(48);
    float sr = hw.AudioSampleRate();
    (void)sr;

    adsr_adsr1.Init(sr);
    adsr_adsr1.SetTime(ADSR_SEG_ATTACK, 0.01f);
    adsr_adsr1.SetTime(ADSR_SEG_DECAY, 0.1f);
    adsr_adsr1.SetSustainLevel(0.7f);
    adsr_adsr1.SetTime(ADSR_SEG_RELEASE, 0.3f);
    oscillator_osc1.Init(sr);
    oscillator_osc1.SetWaveform(Oscillator::WAVE_SIN);
    oscillator_osc1.SetFreq(220.f);
    oscillator_osc1.SetAmp(0.5f);



    hw.StartAudio(AudioCallback);

    while (1) {

        System::Delay(1);
    }
}
