// Auto-generated by Daisypatcher
// Patch: filter_lfo_sweep
// Target: filter_lfo_sweep
// DO NOT EDIT — regenerate from the .dpatch file

#include "daisy_seed.h"
#include "daisysp.h"
#include <cmath>
#include <cstdlib>

using namespace daisy;
using namespace daisysp;

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// Maximum delay-line length (samples). Enough for 2s at 48kHz.
static constexpr size_t CODEGEN_MAX_DELAY = static_cast<size_t>(48000 * 2);

DaisySeed hw;

// --- Node declarations ---
// oscillator osc1
Oscillator oscillator_osc1;
// lfo lfo1
Oscillator lfo_lfo1;
// filter_svf svf1
Svf filter_svf_svf1;

void AudioCallback(AudioHandle::InputBuffer in,
                   AudioHandle::OutputBuffer out,
                   size_t size) {
    float sr = hw.AudioSampleRate();
    for (size_t i = 0; i < size; i++) {
        float in_l = in[0][i];
        float in_r = in[1][i];
        (void)in_l; (void)in_r; (void)sr;

    oscillator_osc1.SetFreq(220.f * powf(2.f, 0.f));
    oscillator_osc1.SetAmp(0.5f * 1.f);
    float oscillator_osc1_out = oscillator_osc1.Process();

    float lfo_lfo1_out = lfo_lfo1.Process() * (1.f) + (0.f);

    filter_svf_svf1.SetFreq((fmaxf(20.f, fminf(20000.f, lfo_lfo1_out))) * powf(2.f, 0.f));
    filter_svf_svf1.SetRes(0.2f);
    filter_svf_svf1.Process(oscillator_osc1_out);
    float filter_svf_svf1_lp = filter_svf_svf1.Low();
    float filter_svf_svf1_hp = filter_svf_svf1.High();
    float filter_svf_svf1_bp = filter_svf_svf1.Band();
    float filter_svf_svf1_notch = filter_svf_svf1.Notch();

        float out_l = filter_svf_svf1_lp;
        float out_r = filter_svf_svf1_lp;
        out[0][i] = out_l;
        out[1][i] = out_r;
    }
}

int main(void) {
    // boost=true moves the H7 to 480MHz so the SAI MCLK ratio lands cleanly
    // on the AK4556's expected bit-clock. Without it the codec DAC can end
    // up silent or VERY quiet even though the callback runs — validated
    // with an LED-in-callback test on 2026-04-21.
    hw.Init(true);
    hw.SetAudioBlockSize(48);
    float sr = hw.AudioSampleRate();
    (void)sr;

    oscillator_osc1.Init(sr);
    oscillator_osc1.SetWaveform(Oscillator::WAVE_POLYBLEP_SAW);
    oscillator_osc1.SetFreq(220.f);
    oscillator_osc1.SetAmp(0.5f);
    lfo_lfo1.Init(sr);
    lfo_lfo1.SetWaveform(Oscillator::WAVE_SIN);
    lfo_lfo1.SetFreq(1.f);
    lfo_lfo1.SetAmp(1.f);
    filter_svf_svf1.Init(sr);
    filter_svf_svf1.SetFreq(1000.f);
    filter_svf_svf1.SetRes(0.2f);



    hw.StartAudio(AudioCallback);

    while (1) {

        System::Delay(1);
    }
}
