// Auto-generated by Daisypatcher
// Patch: preset-recall
// Target: preset_recall
// DO NOT EDIT — regenerate from the .dpatch file

#include "daisy_seed.h"
#include "daisysp.h"
#include <cmath>
#include <cstdlib>

using namespace daisy;
using namespace daisysp;

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// Maximum delay-line length (samples). Enough for 2s at 48kHz.
static constexpr size_t CODEGEN_MAX_DELAY = static_cast<size_t>(48000 * 2);

DaisySeed hw;

// --- Node declarations ---
// Params driven live by a menu leaf (see menuCodegen.ts).
float dp_mp_oscillator_osc1_frequency = 220.f;
float dp_mp_oscillator_osc1_amplitude = 0.4f;
float dp_mp_filter_svf_flt1_frequency = 900.f;
float dp_mp_filter_svf_flt1_resonance = 0.25f;
// --- Presets (see presetCodegen.ts) ---
#define DP_PRESET_COUNT_OK 1
static const int DP_PRESET_COUNT = 3;
static const int DP_PRESET_PARAMS = 4;
// preset 0: Bright
// preset 1: Dark
// preset 2: Mid
static const float dp_preset_table[DP_PRESET_COUNT][DP_PRESET_PARAMS] = {
    { 220.f, 0.4f, 6000.f, 0.15f },
    { 110.f, 0.5f, 240.f, 0.7f },
    { 165.f, 0.45f, 1200.f, 0.4f }
};
static float* const dp_preset_slots[DP_PRESET_PARAMS] = {
    &dp_mp_oscillator_osc1_frequency,
    &dp_mp_oscillator_osc1_amplitude,
    &dp_mp_filter_svf_flt1_frequency,
    &dp_mp_filter_svf_flt1_resonance
};

static inline void dp_preset_apply(int idx) {
    if (idx < 0) idx = 0;
    if (idx >= DP_PRESET_COUNT) idx = DP_PRESET_COUNT - 1;
    for (int i = 0; i < DP_PRESET_PARAMS; i++) {
        *dp_preset_slots[i] = dp_preset_table[idx][i];
    }
}

/* Linear interpolation between two presets. Numeric params only — see the
   header note on why enums cannot come along. */
static inline void dp_preset_morph(int a, int b, float t) {
    if (a < 0) a = 0;
    if (a >= DP_PRESET_COUNT) a = DP_PRESET_COUNT - 1;
    if (b < 0) b = 0;
    if (b >= DP_PRESET_COUNT) b = DP_PRESET_COUNT - 1;
    if (t < 0.f) t = 0.f;
    if (t > 1.f) t = 1.f;
    for (int i = 0; i < DP_PRESET_PARAMS; i++) {
        const float va = dp_preset_table[a][i];
        const float vb = dp_preset_table[b][i];
        *dp_preset_slots[i] = va + (vb - va) * t;
    }
}
// oscillator osc1
Oscillator oscillator_osc1;
// filter_svf flt1
Svf filter_svf_flt1;
// clock clk1
float clock_clk1_phase = 0.f;

void AudioCallback(AudioHandle::InputBuffer in,
                   AudioHandle::OutputBuffer out,
                   size_t size) {
    float sr = hw.AudioSampleRate();
    for (size_t i = 0; i < size; i++) {
        float in_l = in[0][i];
        float in_r = in[1][i];
        (void)in_l; (void)in_r; (void)sr;

    oscillator_osc1.SetFreq(dp_mp_oscillator_osc1_frequency * powf(2.f, 0.f));
    oscillator_osc1.SetAmp(dp_mp_oscillator_osc1_amplitude * 1.f);
    float oscillator_osc1_out = -oscillator_osc1.Process();

    filter_svf_flt1.SetFreq((dp_mp_filter_svf_flt1_frequency) * powf(2.f, 0.f));
    filter_svf_flt1.SetRes(dp_mp_filter_svf_flt1_resonance);
    filter_svf_flt1.Process(oscillator_osc1_out);
    float filter_svf_flt1_lp = filter_svf_flt1.Low();
    float filter_svf_flt1_hp = filter_svf_flt1.High();
    float filter_svf_flt1_bp = filter_svf_flt1.Band();
    float filter_svf_flt1_notch = filter_svf_flt1.Notch();

    (void)filter_svf_flt1_hp;
    (void)filter_svf_flt1_bp;
    (void)filter_svf_flt1_notch;

    clock_clk1_phase += ((96.f) / 60.f) / sr;
    if (clock_clk1_phase >= 1.f) clock_clk1_phase -= 1.f;
    float clock_clk1_out = (clock_clk1_phase < 0.1f) ? 1.f : 0.f;

    static float preset_recall_pre1_prev = 0.f;
    float preset_recall_pre1_t = clock_clk1_out;
    bool preset_recall_pre1_edge = (preset_recall_pre1_t >= 0.5f) && (preset_recall_pre1_prev < 0.5f);
    preset_recall_pre1_prev = preset_recall_pre1_t;
#ifdef DP_PRESET_COUNT_OK
    if (preset_recall_pre1_edge) dp_preset_apply((int)(1.f));
#endif
    float preset_recall_pre1_changed = preset_recall_pre1_edge ? 1.f : 0.f;

    (void)preset_recall_pre1_changed;

        float out_l = filter_svf_flt1_lp;
        float out_r = filter_svf_flt1_lp;
        out[0][i] = out_l;
        out[1][i] = out_r;
    }
}

int main(void) {
    // boost=true moves the H7 to 480MHz so the SAI MCLK ratio lands cleanly
    // on the AK4556's expected bit-clock. Without it the codec DAC can end
    // up silent or VERY quiet even though the callback runs — validated
    // with an LED-in-callback test on 2026-04-21.
    hw.Init(true);
    hw.SetAudioBlockSize(48);
    float sr = hw.AudioSampleRate();
    (void)sr;

    oscillator_osc1.Init(sr);
    oscillator_osc1.SetWaveform(Oscillator::WAVE_POLYBLEP_SAW);
    oscillator_osc1.SetFreq(dp_mp_oscillator_osc1_frequency);
    oscillator_osc1.SetAmp(dp_mp_oscillator_osc1_amplitude);
    filter_svf_flt1.Init(sr);
    filter_svf_flt1.SetFreq(dp_mp_filter_svf_flt1_frequency);
    filter_svf_flt1.SetRes(dp_mp_filter_svf_flt1_resonance);



    hw.StartAudio(AudioCallback);

    while (1) {

        System::Delay(1);
    }
}
