// Auto-generated by Daisypatcher (ESP32-S3 target)
// Patch: granulator_freeze
// Target: granulator_freeze
// DO NOT EDIT — regenerate from the .dpatch file

#include <Arduino.h>
#include <Wire.h>
#include <driver/i2s.h>
#include <math.h>

static const int SAMPLE_RATE = 48000;
static const int BLOCK = 48;
static const i2s_port_t I2S_PORT = I2S_NUM_0;

/*
 * DaisySP's SoftLimit/SoftClip, transliterated.
 *
 * ESP32 builds do not link DaisySP, so any emitter that needs to match a
 * DaisySP-shaped curve has to carry its own copy. Kept here rather than
 * inside one emitter's output because more than one node saturates, and
 * three private copies of the same polynomial is how the two targets
 * drifted apart in the first place.
 */
static inline float dp_soft_clip(float x) {
    if (x < -3.f) return -1.f;
    if (x > 3.f) return 1.f;
    return x * (27.f + x * x) / (27.f + 9.f * x * x);
}
int16_t audio_out_buffer[48 * 2];

// --- Node declarations ---
// oscillator osc1
float oscillator_osc1_phase = 0.f;
// granulator gran1
#ifndef DP_GR_BUF
#define DP_GR_BUF 192002
#endif
#ifndef DP_GR_BUF_FALLBACK
#define DP_GR_BUF_FALLBACK 24000
#endif
float* granulator_gran1_buf = nullptr;
int granulator_gran1_buf_len = 0;
int granulator_gran1_wr = 0; float granulator_gran1_spawn_ctr = 0.f;
int granulator_gran1_active[8] = {0};
float granulator_gran1_gpos[8] = {0}; float granulator_gran1_gstart[8] = {0};
float granulator_gran1_glen[8] = {0}; float granulator_gran1_grate[8] = {0};
uint32_t granulator_gran1_rng = 0xbabebeefu;
// clock clk1
float clock_clk1_phase = 0.f;
// freeze frz1
static float freeze_frz1_buf[24002] = {0};
int freeze_frz1_wr = 0; int freeze_frz1_play = 0; int freeze_frz1_captured = 0;
int freeze_frz1_rec = 0; float freeze_frz1_prev_gate = 0.f;

// --- Hardware state ---
// (no hardware components placed)

static inline void render_block() {
    for (int i = 0; i < BLOCK; i++) {
        float in_l = 0.f, in_r = 0.f;
        (void)in_l; (void)in_r;

    {
        float _f = 220.f * powf(2.f, 0.f);
        oscillator_osc1_phase += _f / (float)SAMPLE_RATE;
        if (oscillator_osc1_phase >= 1.f) oscillator_osc1_phase -= 1.f;
        if (oscillator_osc1_phase < 0.f) oscillator_osc1_phase += 1.f;
    }
    float oscillator_osc1_out = sinf(oscillator_osc1_phase * 6.28318530718f) * 0.5f * 1.f;

    float granulator_gran1_out;
    {
        float _x = (oscillator_osc1_out);
        if (!granulator_gran1_buf) { granulator_gran1_out = _x; } else {
        granulator_gran1_buf[granulator_gran1_wr] = _x;
        granulator_gran1_wr++; if (granulator_gran1_wr >= granulator_gran1_buf_len) granulator_gran1_wr = 0;
        float _jitter = (0.3f);
        float _pitchParam = (0.f);
        float _gs = fmaxf(1.f, ((80.f) / 1000.f) * (float)SAMPLE_RATE);
        float _spawnInt = (float)SAMPLE_RATE / fmaxf(0.001f, (8.f));
        granulator_gran1_spawn_ctr -= 1.f;
        if (granulator_gran1_spawn_ctr <= 0.f) {
            int _slot = -1;
            for (int _s = 0; _s < 8; _s++) if (!granulator_gran1_active[_s]) { _slot = _s; break; }
            if (_slot >= 0) {
                granulator_gran1_rng = granulator_gran1_rng * 1664525u + 1013904223u;
                float _r1 = (granulator_gran1_rng >> 8) / 16777216.f;
                granulator_gran1_rng = granulator_gran1_rng * 1664525u + 1013904223u;
                float _r2 = (granulator_gran1_rng >> 8) / 16777216.f;
                float _jit = (_r1 * 2.f - 1.f) * _jitter;
                float _back = _gs * (1.f + 2.f * _jitter) + _r2 * _jitter * ((float)granulator_gran1_buf_len - _gs - 2.f);
                float _start = (float)granulator_gran1_wr - _gs - _back;
                while (_start < 0.f) _start += (float)granulator_gran1_buf_len;
                while (_start >= (float)granulator_gran1_buf_len) _start -= (float)granulator_gran1_buf_len;
                float _pj = _pitchParam + _jit * 2.f;
                granulator_gran1_active[_slot] = 1;
                granulator_gran1_gpos[_slot] = 0.f;
                granulator_gran1_gstart[_slot] = _start;
                granulator_gran1_glen[_slot] = _gs;
                granulator_gran1_grate[_slot] = powf(2.f, _pj / 12.f);
            }
            granulator_gran1_spawn_ctr += _spawnInt;
        }
        float _wet = 0.f;
        for (int _s = 0; _s < 8; _s++) {
            if (!granulator_gran1_active[_s]) continue;
            float _pos = granulator_gran1_gpos[_s]; float _len = granulator_gran1_glen[_s];
            if (_pos >= _len) { granulator_gran1_active[_s] = 0; continue; }
            float _rp = granulator_gran1_gstart[_s] + _pos;
            while (_rp >= (float)granulator_gran1_buf_len) _rp -= (float)granulator_gran1_buf_len;
            while (_rp < 0.f) _rp += (float)granulator_gran1_buf_len;
            int _r0 = (int)_rp; float _frac = _rp - (float)_r0;
            int _r1 = (_r0 + 1) % granulator_gran1_buf_len;
            float _smp = granulator_gran1_buf[_r0] * (1.f - _frac) + granulator_gran1_buf[_r1] * _frac;
            float _env = 0.5f - 0.5f * cosf(6.28318530718f * _pos / _len);
            _wet += _smp * _env;
            granulator_gran1_gpos[_s] = _pos + granulator_gran1_grate[_s];
        }
        granulator_gran1_out = _x * (1.f - 1.f) + _wet * 1.f;
        }
    }

    clock_clk1_phase += ((120.f) / 60.f) / (float)SAMPLE_RATE;
    if (clock_clk1_phase >= 1.f) clock_clk1_phase -= 1.f;
    float clock_clk1_out = (clock_clk1_phase < 0.1f) ? 1.f : 0.f;

    float freeze_frz1_out;
    {
        float _ms = (120.f); if (_ms < 20.f) _ms = 20.f; else if (_ms > 500.f) _ms = 500.f;
        int _tgt = (int)((_ms / 1000.f) * (float)SAMPLE_RATE);
        if (_tgt > 24000) _tgt = 24000;
        float _x = (granulator_gran1_out);
        float _g = (clock_clk1_out); bool _h = _g > 0.5f;
        if (_h && freeze_frz1_prev_gate <= 0.5f) { freeze_frz1_rec = 1; freeze_frz1_wr = 0; freeze_frz1_captured = 0; }
        if (!_h && freeze_frz1_prev_gate > 0.5f) { freeze_frz1_rec = 0; }
        freeze_frz1_prev_gate = _g;
        if (freeze_frz1_rec) {
            if (freeze_frz1_wr < _tgt) { freeze_frz1_buf[freeze_frz1_wr++] = _x; freeze_frz1_captured = freeze_frz1_wr; }
            else { freeze_frz1_rec = 0; }
        }
        if (freeze_frz1_captured > 0 && _h) {
            if (freeze_frz1_play >= freeze_frz1_captured) freeze_frz1_play = 0;
            freeze_frz1_out = freeze_frz1_buf[freeze_frz1_play++];
        } else {
            freeze_frz1_out = _x; freeze_frz1_play = 0;
        }
    }

        float out_l = freeze_frz1_out;
        float out_r = freeze_frz1_out;
        audio_out_buffer[i*2]     = (int16_t)(fmaxf(-1.f, fminf(1.f, out_l)) * 32767.f);
        audio_out_buffer[i*2 + 1] = (int16_t)(fmaxf(-1.f, fminf(1.f, out_r)) * 32767.f);
    }
}

void setup() {
    Serial.begin(115200);

    // --- Hardware pin setup ---
    // (no hardware init)

    // --- Node init ---
    // Granulator capture buffer: PSRAM if the board has it, heap if not.
    granulator_gran1_buf_len = DP_GR_BUF;
    granulator_gran1_buf = (float*)ps_malloc((size_t)granulator_gran1_buf_len * sizeof(float));
    if (!granulator_gran1_buf) {
        granulator_gran1_buf_len = DP_GR_BUF_FALLBACK;
        granulator_gran1_buf = (float*)malloc((size_t)granulator_gran1_buf_len * sizeof(float));
    }
    if (granulator_gran1_buf) memset(granulator_gran1_buf, 0, (size_t)granulator_gran1_buf_len * sizeof(float));
    else granulator_gran1_buf_len = 0;
    for (int _k = 0; _k < 8; _k++) granulator_gran1_active[_k] = 0;

    // --- I2S audio out ---
    i2s_config_t i2s_cfg = {
        .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_TX),
        .sample_rate = SAMPLE_RATE,
        .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
        .channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT,
        .communication_format = I2S_COMM_FORMAT_STAND_I2S,
        .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,
        .dma_buf_count = 4,
        .dma_buf_len = 48,
        .use_apll = false,
        .tx_desc_auto_clear = true,
        .fixed_mclk = 0
    };
    i2s_pin_config_t pin_cfg = {
        .bck_io_num = 36,
        .ws_io_num = 37,
        .data_out_num = 35,
        .data_in_num = I2S_PIN_NO_CHANGE
    };
    i2s_driver_install(I2S_PORT, &i2s_cfg, 0, nullptr);
    i2s_set_pin(I2S_PORT, &pin_cfg);
    i2s_set_clk(I2S_PORT, SAMPLE_RATE, I2S_BITS_PER_SAMPLE_16BIT, I2S_CHANNEL_STEREO);
}

void loop() {
    // --- Poll hardware (ADC + GPIO) ---
    // (no hardware inputs)

    // --- Slow peripherals (I2C sensors etc). NEVER inside render_block(). ---
    // (none)

    // --- Copy bound hardware values into per-node state ---
    // (no bindings)

    // --- Render one audio block + push to I2S ---
    render_block();
    size_t written = 0;
    i2s_write(I2S_PORT, audio_out_buffer, sizeof(audio_out_buffer), &written, portMAX_DELAY);
}
