// Auto-generated by Daisypatcher (ESP32-S3 target)
// Patch: hw_oled_knob_button
// Target: hw_oled_knob_button
// DO NOT EDIT — regenerate from the .dpatch file

#include <Arduino.h>
#include <Wire.h>
#include <driver/i2s.h>
#include <math.h>

static const int SAMPLE_RATE = 48000;
static const int BLOCK = 48;
static const i2s_port_t I2S_PORT = I2S_NUM_0;

/*
 * DaisySP's SoftLimit/SoftClip, transliterated.
 *
 * ESP32 builds do not link DaisySP, so any emitter that needs to match a
 * DaisySP-shaped curve has to carry its own copy. Kept here rather than
 * inside one emitter's output because more than one node saturates, and
 * three private copies of the same polynomial is how the two targets
 * drifted apart in the first place.
 */
static inline float dp_soft_clip(float x) {
    if (x < -3.f) return -1.f;
    if (x > 3.f) return 1.f;
    return x * (27.f + x * x) / (27.f + 9.f * x * x);
}
int16_t audio_out_buffer[48 * 2];

// --- Node declarations ---
float led_led1_val = 0.f;
// knob_in knob1
float knob_in_knob1_val = 0.f;
// button btn1
float button_btn1_val = 0.f;
// oled oled1
#ifndef DP_OLED_INCLUDED
#define DP_OLED_INCLUDED 1
#include <Adafruit_SSD1306.h>
#endif
Adafruit_SSD1306 oled_oled1(128, 64, &Wire);
float oled_oled1_in_a = 0.f;
float oled_oled1_in_b = 0.f;
float oled_oled1_in_c = 0.f;
float oled_oled1_in_d = 0.f;
float oled_oled1_in_e = 0.f;
float oled_oled1_in_f = 0.f;
int oled_oled1_draw_ctr = 0;

// --- Hardware state ---
float hw_pot_hwpot1_val = 0.f; // Cutoff Knob
float hw_button_hwbtn1_val = 0.f; // Trig Button

static inline void render_block() {
    for (int i = 0; i < BLOCK; i++) {
        float in_l = 0.f, in_r = 0.f;
        (void)in_l; (void)in_r;

    float knob_in_knob1_out = knob_in_knob1_val;

    float button_btn1_out = button_btn1_val;

    led_led1_val = (button_btn1_out);

    // --- OLED oled_oled1: latch inputs, render at ~30 Hz ---
    oled_oled1_in_a = knob_in_knob1_out;
    oled_oled1_in_b = 0.f;
    oled_oled1_in_c = 0.f;
    oled_oled1_in_d = 0.f;
    oled_oled1_in_e = 0.f;
    oled_oled1_in_f = 0.f;
    oled_oled1_draw_ctr++;
    if (oled_oled1_draw_ctr >= (SAMPLE_RATE / 30)) {
        oled_oled1_draw_ctr = 0;
        oled_oled1.clearDisplay();
        oled_oled1.setTextSize(1);
        oled_oled1.setTextColor(SSD1306_WHITE);
        oled_oled1.setCursor(0, 0);
        oled_oled1.print("DAISY");
        { char _buf[24]; snprintf(_buf, sizeof _buf, "%.2f", oled_oled1_in_a);
          oled_oled1.setTextSize(1); oled_oled1.setTextColor(SSD1306_WHITE);
          oled_oled1.setCursor(0, 16); oled_oled1.print(_buf); }
        oled_oled1.display();
    }

        float out_l = 0.f;
        float out_r = 0.f;
        audio_out_buffer[i*2]     = (int16_t)(fmaxf(-1.f, fminf(1.f, out_l)) * 32767.f);
        audio_out_buffer[i*2 + 1] = (int16_t)(fmaxf(-1.f, fminf(1.f, out_r)) * 32767.f);
    }
}

void setup() {
    Serial.begin(115200);

    // --- Hardware pin setup ---
    analogRead(1); // prime ADC for Cutoff Knob
    pinMode(0, INPUT_PULLUP); // Trig Button
    pinMode(21, OUTPUT); // Status LED
    Wire.begin(8, 9);

    // --- Node init ---
    oled_oled1.begin(SSD1306_SWITCHCAPVCC, 0x3C);
    oled_oled1.clearDisplay();
    oled_oled1.display();

    // --- I2S audio out ---
    i2s_config_t i2s_cfg = {
        .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_TX),
        .sample_rate = SAMPLE_RATE,
        .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
        .channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT,
        .communication_format = I2S_COMM_FORMAT_STAND_I2S,
        .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,
        .dma_buf_count = 4,
        .dma_buf_len = 48,
        .use_apll = false,
        .tx_desc_auto_clear = true,
        .fixed_mclk = 0
    };
    i2s_pin_config_t pin_cfg = {
        .bck_io_num = 36,
        .ws_io_num = 37,
        .data_out_num = 35,
        .data_in_num = I2S_PIN_NO_CHANGE
    };
    i2s_driver_install(I2S_PORT, &i2s_cfg, 0, nullptr);
    i2s_set_pin(I2S_PORT, &pin_cfg);
    i2s_set_clk(I2S_PORT, SAMPLE_RATE, I2S_BITS_PER_SAMPLE_16BIT, I2S_CHANNEL_STEREO);
}

void loop() {
    // --- Poll hardware (ADC + GPIO) ---
    hw_pot_hwpot1_val = (float)analogRead(1) / 4095.f; // ADC chan 0
    hw_button_hwbtn1_val = digitalRead(0) == LOW ? 1.f : 0.f;

    // --- Slow peripherals (I2C sensors etc). NEVER inside render_block(). ---
    // (none)

    // --- Copy bound hardware values into per-node state ---
    knob_in_knob1_val = hw_pot_hwpot1_val;
    button_btn1_val = hw_button_hwbtn1_val;
    digitalWrite(21, (led_led1_val > 0.5f) ? HIGH : LOW);

    // --- Render one audio block + push to I2S ---
    render_block();
    size_t written = 0;
    i2s_write(I2S_PORT, audio_out_buffer, sizeof(audio_out_buffer), &written, portMAX_DELAY);
}
