// Auto-generated by Daisypatcher
// Patch: hw_oled_knob_button
// Target: hw_oled_knob_button
// DO NOT EDIT — regenerate from the .dpatch file

#include "daisy_seed.h"
#include "daisysp.h"
#include <cmath>
#include <cstdlib>

using namespace daisy;
using namespace daisysp;

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// Maximum delay-line length (samples). Enough for 2s at 48kHz.
static constexpr size_t CODEGEN_MAX_DELAY = static_cast<size_t>(48000 * 2);

DaisySeed hw;

// --- Node declarations ---
// knob_in knob1
float knob_in_knob1_val = 0.f;
// button btn1
float button_btn1_val = 0.f;
// oled oled1
#include "dev/oled_ssd130x.h"
using oled_oled1_Type = OledDisplay<SSD130xI2c128x64Driver>;
oled_oled1_Type oled_oled1;
float oled_oled1_in_a = 0.f;
float oled_oled1_in_b = 0.f;
float oled_oled1_in_c = 0.f;
float oled_oled1_in_d = 0.f;
float oled_oled1_in_e = 0.f;
float oled_oled1_in_f = 0.f;
uint32_t oled_oled1_last_frame_ms = 0;
// Hardware layout
// Hardware: ADC channel values (0..1), one per placed pot / CV jack.
float hw_pot_hwpot1_val = 0.f;
GPIO hw_button_hwbtn1_gpio;
GPIO hw_led_hwled1_gpio;

void AudioCallback(AudioHandle::InputBuffer in,
                   AudioHandle::OutputBuffer out,
                   size_t size) {
    float sr = hw.AudioSampleRate();
    for (size_t i = 0; i < size; i++) {
        float in_l = in[0][i];
        float in_r = in[1][i];
        (void)in_l; (void)in_r; (void)sr;

    float knob_in_knob1_out = hw_pot_hwpot1_val;

    float button_btn1_out = (hw_button_hwbtn1_gpio.Read() ? 0.f : 1.f);

    hw_led_hwled1_gpio.Write(((button_btn1_out) > 0.5f) ? 1 : 0);

    // --- OLED oled_oled1: latch input samples for DrawFrame() ---
    oled_oled1_in_a = knob_in_knob1_out;
    oled_oled1_in_b = 0.f;
    oled_oled1_in_c = 0.f;
    oled_oled1_in_d = 0.f;
    oled_oled1_in_e = 0.f;
    oled_oled1_in_f = 0.f;
    // DrawFrame body (call from while(1) at ~30 Hz):
    //   oled_oled1.Fill(false);
    //   oled_oled1.SetCursor(0, 0); oled_oled1.WriteString("DAISY", Font_6x8, true);
    //   { char buf[24]; snprintf(buf, sizeof buf, "%.2f", oled_oled1_in_a);
    //     oled_oled1.SetCursor(0, 16); oled_oled1.WriteString(buf, Font_6x8, true); }
    //   oled_oled1.Update();

        float out_l = 0.f;
        float out_r = 0.f;
        out[0][i] = out_l;
        out[1][i] = out_r;
    }
}

int main(void) {
    // boost=true moves the H7 to 480MHz so the SAI MCLK ratio lands cleanly
    // on the AK4556's expected bit-clock. Without it the codec DAC can end
    // up silent or VERY quiet even though the callback runs — validated
    // with an LED-in-callback test on 2026-04-21.
    hw.Init(true);
    hw.SetAudioBlockSize(48);
    float sr = hw.AudioSampleRate();
    (void)sr;

    // --- OLED: Main OLED ---
    {
        oled_oled1_Type::Config oled_cfg;
        oled_cfg.driver_config.transport_config.i2c_config.mode   = I2CHandle::Config::Mode::I2C_MASTER;
        oled_cfg.driver_config.transport_config.i2c_config.periph = I2CHandle::Config::Peripheral::I2C_1;
        oled_cfg.driver_config.transport_config.i2c_config.speed  = I2CHandle::Config::Speed::I2C_400KHZ;
        oled_cfg.driver_config.transport_config.i2c_config.pin_config.scl = hw.GetPin(11);
        oled_cfg.driver_config.transport_config.i2c_config.pin_config.sda = hw.GetPin(12);
        oled_cfg.driver_config.transport_config.i2c_address = 0x3C;
        oled_oled1.Init(oled_cfg);
    }

    // --- ADC: 1 channel ---
    AdcChannelConfig hw_adc_cfg[1];
    hw_adc_cfg[0].InitSingle(hw.GetPin(15 + 6)); // Cutoff Knob (D15)
    hw.adc.Init(hw_adc_cfg, 1);
    hw.adc.Start();

    // --- button: Trig Button ---
    hw_button_hwbtn1_gpio.Init(hw.GetPin(0), GPIO::Mode::INPUT, GPIO::Pull::PULLUP);

    // --- led: Status LED ---
    hw_led_hwled1_gpio.Init(hw.GetPin(13), GPIO::Mode::OUTPUT);

    // --- I2C1 (OLED / sensors) ---
    I2CHandle::Config i2c_cfg;
    i2c_cfg.periph = I2CHandle::Config::Peripheral::I2C_1;
    i2c_cfg.speed  = I2CHandle::Config::Speed::I2C_400KHZ;
    i2c_cfg.mode   = I2CHandle::Config::Mode::I2C_MASTER;
    i2c_cfg.pin_config.scl = hw.GetPin(11);
    i2c_cfg.pin_config.sda = hw.GetPin(12);
    // TODO: call into OledDisplay::Init with this i2c_cfg for SSD1306.

    hw.StartAudio(AudioCallback);

    while (1) {
        hw_pot_hwpot1_val = hw.adc.GetFloat(0);
        System::Delay(1);
    }
}
