// Auto-generated by Daisypatcher
// Patch: xfade_mixer_math
// Target: xfade_mixer_math
// DO NOT EDIT — regenerate from the .dpatch file

#include "daisy_seed.h"
#include "daisysp.h"
#include <cmath>
#include <cstdlib>

using namespace daisy;
using namespace daisysp;

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// Maximum delay-line length (samples). Enough for 2s at 48kHz.
static constexpr size_t CODEGEN_MAX_DELAY = static_cast<size_t>(48000 * 2);

DaisySeed hw;

// --- Node declarations ---
// oscillator osc1
Oscillator oscillator_osc1;
// noise noise1
WhiteNoise noise_noise1;
// lfo lfo1
Oscillator lfo_lfo1;

void AudioCallback(AudioHandle::InputBuffer in,
                   AudioHandle::OutputBuffer out,
                   size_t size) {
    float sr = hw.AudioSampleRate();
    for (size_t i = 0; i < size; i++) {
        float in_l = in[0][i];
        float in_r = in[1][i];
        (void)in_l; (void)in_r; (void)sr;

    oscillator_osc1.SetFreq(220.f * powf(2.f, 0.f));
    oscillator_osc1.SetAmp(0.5f * 1.f);
    float oscillator_osc1_out = oscillator_osc1.Process();

    float noise_noise1_out = noise_noise1.Process();

    float lfo_lfo1_out = lfo_lfo1.Process() * (1.f) + (0.f);

    float crossfade_xf1_out;
    {
        float m = (fmaxf(0.f, fminf(1.f, lfo_lfo1_out))) + (0.f);
        if (m < 0.f) m = 0.f; if (m > 1.f) m = 1.f;
        float _ga = cosf(m * 1.57079632679f);
        float _gb = sinf(m * 1.57079632679f);
        crossfade_xf1_out = (oscillator_osc1_out) * _ga + (noise_noise1_out) * _gb;
    }

    float mixer4_mix1_out = (crossfade_xf1_out) * (1.f) + (0.f) * (1.f) + (0.f) * (1.f) + (0.f) * (1.f);

        float out_l = mixer4_mix1_out;
        float out_r = mixer4_mix1_out;
        out[0][i] = out_l;
        out[1][i] = out_r;
    }
}

int main(void) {
    // boost=true moves the H7 to 480MHz so the SAI MCLK ratio lands cleanly
    // on the AK4556's expected bit-clock. Without it the codec DAC can end
    // up silent or VERY quiet even though the callback runs — validated
    // with an LED-in-callback test on 2026-04-21.
    hw.Init(true);
    hw.SetAudioBlockSize(48);
    float sr = hw.AudioSampleRate();
    (void)sr;

    oscillator_osc1.Init(sr);
    oscillator_osc1.SetWaveform(Oscillator::WAVE_SIN);
    oscillator_osc1.SetFreq(220.f);
    oscillator_osc1.SetAmp(0.5f);
    noise_noise1.Init();
    noise_noise1.SetAmp(0.3f);
    lfo_lfo1.Init(sr);
    lfo_lfo1.SetWaveform(Oscillator::WAVE_SIN);
    lfo_lfo1.SetFreq(1.f);
    lfo_lfo1.SetAmp(1.f);



    hw.StartAudio(AudioCallback);

    while (1) {

        System::Delay(1);
    }
}
