// Auto-generated by Daisypatcher (ESP32-S3 target)
// Patch: karplus_seq
// Target: karplus_seq
// DO NOT EDIT — regenerate from the .dpatch file

#include <Arduino.h>
#include <Wire.h>
#include <driver/i2s.h>
#include <math.h>

static const int SAMPLE_RATE = 48000;
static const int BLOCK = 48;
static const i2s_port_t I2S_PORT = I2S_NUM_0;
int16_t audio_out_buffer[48 * 2];

// --- Node declarations ---
// clock clk1
float clock_clk1_phase = 0.f;
// step_seq seq1
uint32_t step_seq_seq1_step = 0; float step_seq_seq1_prev_clk = 0.f; float step_seq_seq1_prev_rst = 0.f;
// karplus kp1
static float karplus_kp1_buf[2404] = {0};
int karplus_kp1_wr = 0; int karplus_kp1_len = 2;
float karplus_kp1_lp = 0.f; float karplus_kp1_prev_trig = 0.f;
int karplus_kp1_auto_ctr = 0; uint32_t karplus_kp1_rng = 0x2fe9ab01u;

// --- Hardware state ---
// (no hardware components placed)

static inline void render_block() {
    for (int i = 0; i < BLOCK; i++) {
        float in_l = 0.f, in_r = 0.f;
        (void)in_l; (void)in_r;

    clock_clk1_phase += ((120.f) / 60.f) / (float)SAMPLE_RATE;
    if (clock_clk1_phase >= 1.f) clock_clk1_phase -= 1.f;
    float clock_clk1_out = (clock_clk1_phase < 0.1f) ? 1.f : 0.f;

    static const float step_seq_seq1_steps[8] = { 0.f, 0.2f, 0.4f, 0.1f, 0.f, 0.f, 0.f, 0.f };
    static const float step_seq_seq1_gates[8] = { 1.f, 1.f, 1.f, 1.f, 0.f, 0.f, 0.f, 0.f };
    {
        float _ci = clock_clk1_out; float _ri = 0.f;
        if (_ri > 0.5f && step_seq_seq1_prev_rst <= 0.5f) step_seq_seq1_step = 0;
        step_seq_seq1_prev_rst = _ri;
        if (_ci > 0.5f && step_seq_seq1_prev_clk <= 0.5f) step_seq_seq1_step = (step_seq_seq1_step + 1u) & 7u;
        step_seq_seq1_prev_clk = _ci;
    }
    float step_seq_seq1_cv = step_seq_seq1_steps[step_seq_seq1_step];
    float step_seq_seq1_gate = step_seq_seq1_gates[step_seq_seq1_step] * ((clock_clk1_out) > 0.5f ? 1.f : 0.f);

    {
        float _freq = fmaxf(20.f, fminf(2000.f, step_seq_seq1_cv));
        float _fb = 0.99f;
        float _damping = 0.5f;
        int _target = (int)((float)SAMPLE_RATE / fmaxf(_freq, 20.f));
        if (_target < 2) _target = 2; if (_target > 2400) _target = 2400;
        karplus_kp1_len = _target;
        float _lp_coef = _damping * 0.95f;
        int _auto_period = 0;
        float _tv = (step_seq_seq1_gate);
        bool _edge = (_tv >= 0.5f) && (karplus_kp1_prev_trig < 0.5f);
        karplus_kp1_prev_trig = _tv;
        if (_edge) {
            for (int _k = 0; _k < karplus_kp1_len; _k++) {
                karplus_kp1_rng = karplus_kp1_rng * 1664525u + 1013904223u;
                karplus_kp1_buf[_k] = ((karplus_kp1_rng >> 8) / 16777216.f) * 2.f - 1.f;
            }
            karplus_kp1_wr = 0; karplus_kp1_lp = 0.f;
        }
        if (_auto_period > 0) {
            karplus_kp1_auto_ctr++;
            if (karplus_kp1_auto_ctr >= _auto_period) {
                karplus_kp1_auto_ctr = 0;
                for (int _k = 0; _k < karplus_kp1_len; _k++) {
                    karplus_kp1_rng = karplus_kp1_rng * 1664525u + 1013904223u;
                    karplus_kp1_buf[_k] = ((karplus_kp1_rng >> 8) / 16777216.f) * 2.f - 1.f;
                }
                karplus_kp1_wr = 0; karplus_kp1_lp = 0.f;
            }
        } else {
            karplus_kp1_auto_ctr = 0;
        }
        int _ri = karplus_kp1_wr % karplus_kp1_len;
        float _s = karplus_kp1_buf[_ri];
        karplus_kp1_lp = _s * (1.f - _lp_coef) + karplus_kp1_lp * _lp_coef;
        float _next = karplus_kp1_lp * _fb;
        if (_next > 1.f) _next = 1.f; else if (_next < -1.f) _next = -1.f;
        karplus_kp1_buf[_ri] = _next;
        karplus_kp1_wr++; if (karplus_kp1_wr >= karplus_kp1_len) karplus_kp1_wr -= karplus_kp1_len;
        float karplus_kp1_out = _s;
    }

        float out_l = karplus_kp1_out;
        float out_r = karplus_kp1_out;
        audio_out_buffer[i*2]     = (int16_t)(fmaxf(-1.f, fminf(1.f, out_l)) * 32767.f);
        audio_out_buffer[i*2 + 1] = (int16_t)(fmaxf(-1.f, fminf(1.f, out_r)) * 32767.f);
    }
}

void setup() {
    Serial.begin(115200);

    // --- Hardware pin setup ---
    // (no hardware init)

    // --- Node init ---
    karplus_kp1_len = 218;

    // --- I2S audio out ---
    i2s_config_t i2s_cfg = {
        .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_TX),
        .sample_rate = SAMPLE_RATE,
        .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
        .channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT,
        .communication_format = I2S_COMM_FORMAT_STAND_I2S,
        .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,
        .dma_buf_count = 4,
        .dma_buf_len = 48,
        .use_apll = false,
        .tx_desc_auto_clear = true,
        .fixed_mclk = 0
    };
    i2s_pin_config_t pin_cfg = {
        .bck_io_num = 36,
        .ws_io_num = 37,
        .data_out_num = 35,
        .data_in_num = I2S_PIN_NO_CHANGE
    };
    i2s_driver_install(I2S_PORT, &i2s_cfg, 0, nullptr);
    i2s_set_pin(I2S_PORT, &pin_cfg);
    i2s_set_clk(I2S_PORT, SAMPLE_RATE, I2S_BITS_PER_SAMPLE_16BIT, I2S_CHANNEL_STEREO);
}

void loop() {
    // --- Poll hardware (ADC + GPIO) ---
    // (no hardware inputs)

    // --- Copy bound hardware values into per-node state ---
    // (no bindings)

    // --- Render one audio block + push to I2S ---
    render_block();
    size_t written = 0;
    i2s_write(I2S_PORT, audio_out_buffer, sizeof(audio_out_buffer), &written, portMAX_DELAY);
}
