// Auto-generated by Daisypatcher (ESP32-S3 target)
// Patch: drums_kit
// Target: drums_kit
// DO NOT EDIT — regenerate from the .dpatch file

#include <Arduino.h>
#include <Wire.h>
#include <driver/i2s.h>
#include <math.h>

static const int SAMPLE_RATE = 48000;
static const int BLOCK = 48;
static const i2s_port_t I2S_PORT = I2S_NUM_0;
int16_t audio_out_buffer[48 * 2];

// --- Node declarations ---
// clock clk1
float clock_clk1_phase = 0.f;
// drum_kick kick1
float drum_kick_kick1_phase = 0.f; float drum_kick_kick1_amp = 0.f; float drum_kick_kick1_pitch_env = 0.f;
float drum_kick_kick1_atk = 0.f; int drum_kick_kick1_attacking = 0; float drum_kick_kick1_prev = 0.f;
// drum_snare snare1
float drum_snare_snare1_p1 = 0.f; float drum_snare_snare1_p2 = 0.f; float drum_snare_snare1_amp = 0.f;
float drum_snare_snare1_hp = 0.f; float drum_snare_snare1_prev = 0.f; uint32_t drum_snare_snare1_rng = 0x9ab17c1u;
// drum_hat hat1
float drum_hat_hat1_ph[6] = {0}; float drum_hat_hat1_amp = 0.f; float drum_hat_hat1_prev = 0.f;
float drum_hat_hat1_bpLow = 0.f; float drum_hat_hat1_bpBand = 0.f;

// --- Hardware state ---
// (no hardware components placed)

static inline void render_block() {
    for (int i = 0; i < BLOCK; i++) {
        float in_l = 0.f, in_r = 0.f;
        (void)in_l; (void)in_r;

    clock_clk1_phase += ((120.f) / 60.f) / (float)SAMPLE_RATE;
    if (clock_clk1_phase >= 1.f) clock_clk1_phase -= 1.f;
    float clock_clk1_out = (clock_clk1_phase < 0.1f) ? 1.f : 0.f;

    {
        float _tune = 60.f;
        float _decay_s = 0.35f;
        float _punch = 0.5f;
        float _dec = fmaxf(0.05f, _decay_s);
        float _amp_coef = expf(-1.f / (_dec * (float)SAMPLE_RATE));
        float _pitch_coef = expf(-1.f / (0.03f * (float)SAMPLE_RATE));
        float _atk_seconds = 0.008f - _punch * 0.007f;
        float _atk_inc = 1.f / (_atk_seconds * (float)SAMPLE_RATE);
        float _topMul = 1.f + 0.6f * 2.f;
        float _tv = (clock_clk1_out);
        if (_tv >= 0.5f && drum_kick_kick1_prev < 0.5f) {
            drum_kick_kick1_pitch_env = 1.f; drum_kick_kick1_amp = 0.f; drum_kick_kick1_atk = 0.f; drum_kick_kick1_attacking = 1; drum_kick_kick1_phase = 0.f;
        }
        drum_kick_kick1_prev = _tv;
        if (drum_kick_kick1_attacking) {
            drum_kick_kick1_atk += _atk_inc;
            if (drum_kick_kick1_atk >= 1.f) { drum_kick_kick1_atk = 1.f; drum_kick_kick1_attacking = 0; drum_kick_kick1_amp = 1.f; }
            else drum_kick_kick1_amp = drum_kick_kick1_atk;
        } else {
            drum_kick_kick1_amp *= _amp_coef;
        }
        drum_kick_kick1_pitch_env *= _pitch_coef;
        float _f = _tune * (1.f + (_topMul - 1.f) * drum_kick_kick1_pitch_env);
        float _inc = 6.28318530718f * _f / (float)SAMPLE_RATE;
        float _y = sinf(drum_kick_kick1_phase) * drum_kick_kick1_amp;
        if (_y > 1.f) _y = 1.f; else if (_y < -1.f) _y = -1.f;
        drum_kick_kick1_phase += _inc;
        if (drum_kick_kick1_phase >= 6.28318530718f) drum_kick_kick1_phase -= 6.28318530718f;
        float drum_kick_kick1_out = _y;
    }

    {
        float _tune = 200.f;
        float _decay_s = 0.2f;
        float _tone = 0.5f;
        float _dec = fmaxf(0.05f, _decay_s);
        float _amp_coef = expf(-1.f / (_dec * (float)SAMPLE_RATE));
        float _lp_coef = expf(-6.28318530718f * 1000.f / (float)SAMPLE_RATE);
        float _inc1 = 6.28318530718f * _tune / (float)SAMPLE_RATE;
        float _inc2 = 6.28318530718f * (_tune * 1.59f) / (float)SAMPLE_RATE;
        float _tv = (clock_clk1_out);
        if (_tv >= 0.5f && drum_snare_snare1_prev < 0.5f) { drum_snare_snare1_amp = 1.f; drum_snare_snare1_p1 = 0.f; drum_snare_snare1_p2 = 0.f; }
        drum_snare_snare1_prev = _tv;
        float _t1 = drum_snare_snare1_p1 / 6.28318530718f; float _b1 = 4.f * fabsf(_t1 - 0.5f) - 1.f;
        float _t2 = drum_snare_snare1_p2 / 6.28318530718f; float _b2 = 4.f * fabsf(_t2 - 0.5f) - 1.f;
        float _body = (_b1 + _b2) * 0.5f;
        drum_snare_snare1_rng = drum_snare_snare1_rng * 1664525u + 1013904223u;
        float _w = ((drum_snare_snare1_rng >> 8) / 16777216.f) * 2.f - 1.f;
        drum_snare_snare1_hp = drum_snare_snare1_hp * _lp_coef + _w * (1.f - _lp_coef);
        float _noise = _w - drum_snare_snare1_hp;
        float _y = (_body * (1.f - _tone) + _noise * _tone) * drum_snare_snare1_amp;
        drum_snare_snare1_amp *= _amp_coef;
        if (_y > 1.f) _y = 1.f; else if (_y < -1.f) _y = -1.f;
        drum_snare_snare1_p1 += _inc1; if (drum_snare_snare1_p1 >= 6.28318530718f) drum_snare_snare1_p1 -= 6.28318530718f;
        drum_snare_snare1_p2 += _inc2; if (drum_snare_snare1_p2 >= 6.28318530718f) drum_snare_snare1_p2 -= 6.28318530718f;
        float drum_snare_snare1_out = _y;
    }

    {
        const float _ratios[6] = { 2.f, 3.f, 4.16f, 5.43f, 6.79f, 8.21f };
        float _decay_s = 0.08f;
        float _tone = 0.7f;
        float _dec = fmaxf(0.01f, _decay_s);
        float _amp_coef = expf(-1.f / (_dec * (float)SAMPLE_RATE));
        float _base = 40.f;
        float _ny = (float)SAMPLE_RATE * 0.5f;
        float _bpF = 8000.f * _tone; if (_bpF > _ny * 0.9f) _bpF = _ny * 0.9f;
        float _f = 2.f * sinf(3.14159265f * _bpF / (float)SAMPLE_RATE);
        float _q = 0.5f;
        float _tv = (clock_clk1_out);
        if (_tv >= 0.5f && drum_hat_hat1_prev < 0.5f) {
            drum_hat_hat1_amp = 1.f; drum_hat_hat1_bpLow = 0.f; drum_hat_hat1_bpBand = 0.f;
            for (int _k = 0; _k < 6; _k++) drum_hat_hat1_ph[_k] = 0.f;
        }
        drum_hat_hat1_prev = _tv;
        float _mix = 0.f;
        for (int _k = 0; _k < 6; _k++) _mix += (drum_hat_hat1_ph[_k] < 3.14159265f ? 1.f : -1.f);
        _mix /= 6.f;
        for (int _k = 0; _k < 6; _k++) {
            drum_hat_hat1_ph[_k] += 6.28318530718f * _base * _ratios[_k] / (float)SAMPLE_RATE;
            if (drum_hat_hat1_ph[_k] >= 6.28318530718f) drum_hat_hat1_ph[_k] -= 6.28318530718f;
        }
        float _high = _mix - drum_hat_hat1_bpLow - _q * drum_hat_hat1_bpBand;
        drum_hat_hat1_bpBand += _f * _high;
        drum_hat_hat1_bpLow  += _f * drum_hat_hat1_bpBand;
        float _y = drum_hat_hat1_bpBand * drum_hat_hat1_amp;
        drum_hat_hat1_amp *= _amp_coef;
        if (_y > 1.f) _y = 1.f; else if (_y < -1.f) _y = -1.f;
        float drum_hat_hat1_out = _y;
    }

    float mixer4_mix1_out = (drum_kick_kick1_out) * (1.f) + (drum_snare_snare1_out) * (1.f) + (drum_hat_hat1_out) * (1.f) + (0.f) * (1.f);

        float out_l = mixer4_mix1_out;
        float out_r = mixer4_mix1_out;
        audio_out_buffer[i*2]     = (int16_t)(fmaxf(-1.f, fminf(1.f, out_l)) * 32767.f);
        audio_out_buffer[i*2 + 1] = (int16_t)(fmaxf(-1.f, fminf(1.f, out_r)) * 32767.f);
    }
}

void setup() {
    Serial.begin(115200);

    // --- Hardware pin setup ---
    // (no hardware init)

    // --- Node init ---


    // --- I2S audio out ---
    i2s_config_t i2s_cfg = {
        .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_TX),
        .sample_rate = SAMPLE_RATE,
        .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
        .channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT,
        .communication_format = I2S_COMM_FORMAT_STAND_I2S,
        .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,
        .dma_buf_count = 4,
        .dma_buf_len = 48,
        .use_apll = false,
        .tx_desc_auto_clear = true,
        .fixed_mclk = 0
    };
    i2s_pin_config_t pin_cfg = {
        .bck_io_num = 36,
        .ws_io_num = 37,
        .data_out_num = 35,
        .data_in_num = I2S_PIN_NO_CHANGE
    };
    i2s_driver_install(I2S_PORT, &i2s_cfg, 0, nullptr);
    i2s_set_pin(I2S_PORT, &pin_cfg);
    i2s_set_clk(I2S_PORT, SAMPLE_RATE, I2S_BITS_PER_SAMPLE_16BIT, I2S_CHANNEL_STEREO);
}

void loop() {
    // --- Poll hardware (ADC + GPIO) ---
    // (no hardware inputs)

    // --- Copy bound hardware values into per-node state ---
    // (no bindings)

    // --- Render one audio block + push to I2S ---
    render_block();
    size_t written = 0;
    i2s_write(I2S_PORT, audio_out_buffer, sizeof(audio_out_buffer), &written, portMAX_DELAY);
}
